-- 0424_routing_no_reasoner_agentic.sql
-- Fix qualita' intervento agentico: o4-mini (reasoner openai o-series) era nella
-- routing matrix SOLO per i task AGENTICI debug/fix (debug economica+veloce,
-- fix_complesso economica+veloce, fix_semplice bilanciata). Su questi task (tool
-- use + chat italiana) e' inadatto: risponde in INGLESE ("Got it. Acting now...")
-- e DESCRIVE i passi invece di emettere tool-call, ignorando la direttiva lingua
-- di system.nexus_base. Esito osservato: l'agente "non risponde con azione dopo
-- 3 tentativi" -> abort, output misto italiano/inglese, nessun edit applicato.
-- Sostituito con gpt-4o-mini (tool-caller openai standard, rispetta l'italiano e
-- le tool-call) sulle stesse righe. Idempotente.
-- FOLLOW-UP (hardening): policy di capability che escluda i reasoner inglesi puri
-- dai task agentici ALLA FONTE (catalog/selezione), cosi' un nuovo reasoner
-- inadatto non rientri in matrix; vedi reference qualita' intervento.
UPDATE nexus_routing_matrix SET model_id = 'gpt-4o-mini' WHERE model_id = 'o4-mini';
