-- Migrazione 0743: le direttive condivise tornano ai modelli.
--
-- MISURATO sul META vivo il 19/08/2026: nexus_shared_directives ha 3 righe
-- attive (project_isolation 2883 char, anti_narration, config_restart) e i
-- suoi UNICI lettori sono il CRUD admin e una pagina UI. Nessun compositore
-- di prompt la legge: l'iniettore viveva in brain/prompt_registry.py e il
-- porting zero-Python (75a6d621, 27/06) lo ha cancellato con tutto il brain.
-- La tabella e' sopravvissuta all'unico codice che la usava, e da 53 giorni
-- nessun modello riceve le regole di isolamento progetto.
--
-- La 0135 aveva fatto la meta' giusta del lavoro (una sola casa per la
-- direttiva, regola L) e lasciato scoperta l'altra: nessuno ha verificato che
-- il canale nuovo arrivasse (regola O).
--
-- COSA NON FA QUESTA MIGRAZIONE, e perche'.
-- La prima stesura ripristinava anche 12 blocchi che la mig 0437 aveva
-- cancellato da agent.coder.base / tester.base / general.debugger riscrivendo
-- il blob per intero. La review lo ha respinto con una misura che regge:
-- ZERO delle 21 figure in nexus_subagent_definitions usa un prompt `agent.*`
-- (usano tutte `subagent.*`), quindi quei blocchi sarebbero tornati su righe
-- che quasi nessuno compone, duplicando 3891 caratteri sull'unico `agent.*`
-- ancora raggiungibile. Il difetto della riscrittura integrale resta reale ed
-- e' chiuso dalla 0744, che lo rende impossibile da ripetere in silenzio.
--
-- ============================================================================
-- PARTE A — perimetro di `nexus_shared_directives`
-- ============================================================================
--
-- La 0135 crea la tabella e RIMUOVE dai template le copie inline di
-- <safety_progetto> (0096) e <anti_narration> (0127), perche' l'iniezione a
-- runtime le avrebbe rimesse. L'iniettore era brain/agents/prompt_registry.py
-- (fc7db83e, 12/05/2026); il porting zero-Python (75a6d621, 27/06/2026) ha
-- cancellato il brain e con esso l'unico consumatore. Dal 27/06 al 19/08/2026
-- nessun modello ha ricevuto quelle direttive: 53 giorni in cui le regole di
-- isolamento progetto (cleanup Docker filtrato, container ideai-* intoccabili,
-- scope alla project_root) non erano nel contesto di nessun agente.
--
-- Il consumatore nuovo e' crates/nexus-prompt/src/direttive.rs, innestato nei
-- tre compositori di system prompt. Qui si corregge il solo DATO che gli
-- impedirebbe di raggiungere il contesto per cui la direttiva era nata.
--
-- `project_isolation` ha scope 'agent', ma la sua stessa `description` dice
-- «Applicato a tutti gli agent.* + system.nexus_base» e la 0096 — che la riga
-- dichiara come propria origine — ha per bersagli system.nexus_base,
-- agent.coder.base e agent.general.debugger. La riga e' incoerente con se'
-- stessa; l'incoerenza non si e' mai vista perche' l'iniettore Python caricava
-- solo le chiavi `agent.%` e lo scope 'system' era codice morto. Il valore
-- giusto e' 'all'.
--
-- Le altre due NON si toccano: `anti_narration` (0127) aveva per bersaglio
-- `key LIKE 'agent.%'` e `config_restart` (0456) nasce dichiarando 'agent'.
-- Allargarle a system.nexus_base sarebbe inventare un perimetro che nessuna
-- migrazione ha mai scritto. Restano configurazione: un UPDATE dal pannello
-- admin le allarga senza redeploy (regola G).
--
-- ============================================================================
-- PARTE B — i blocchi persi da tre prompt riscritti per intero
-- ============================================================================
--
-- La 0437 (02/07) esegue `SET content = $$LINGUA: ...$$` su agent.coder.base e
-- agent.tester.base, la 0438 su agent.general.debugger. Il loro commento
-- dichiara «Tutto il resto del prompt resta invariato»: e' vero rispetto alla
-- struttura della 0086, falso rispetto a tutto cio' che le migrazioni
-- 0096-0434 vi avevano APPESO. Un prompt e' un blob di testo: chi lo riscrive
-- non ha modo di sapere che cosa sta buttando via, e nessun guard se ne
-- accorge — un blocco che non arriva non fa fallire niente.
--
-- PROVA ASIMMETRICA (META vivo, 19/08/2026): le 0192 e 0225 aggiornano
-- system.nexus_base E agent.coder.base nella STESSA transazione.
--   chiave                  | attachment_access | knowledge_graph_tools
--   system.nexus_base       | presente          | presente
--   agent.coder.base        | ASSENTE           | ASSENTE
-- Stessa migrazione, due bersagli: quello mai riscritto per intero ha
-- conservato i blocchi. Contro-prova: agent.reviewer.general, bersaglio della
-- 0137 e mai riscritto, ha ancora <operatore_nexus>.
--
-- COME si ripristina: NON ricopiando il testo a mano. Il blocco si ESTRAE
-- dalla copia sopravvissuta in system.nexus_base, che e' anche la piu'
-- AGGIORNATA — la 0396 e la 0434 hanno riscritto <port_allocation> con un
-- `regexp_replace` gated su `content LIKE '%<port_allocation>%'`, quindi
-- coder.base, avendolo perso, e' stato saltato da entrambe; e la 0674 ha
-- ristretto la NOTA di <operatore_nexus> al solo nexus_base. Copiare dal
-- donatore porta anche quegli emendamenti.
--
-- L'estrazione prende l'ULTIMA apertura PRIMA della chiusura, mai la prima:
-- in system.nexus_base <operatore_nexus> compare 2 volte (la prima e' una
-- MENZIONE in prosa) e <port_allocation> 3 volte. Un `<tag>.*?</tag>` dalla
-- prima occorrenza avrebbe copiato 5841 caratteri invece di 2754, cioe' la
-- menzione piu' tutto il testo interposto. E' la stessa trappola di regexp che
-- la 0674 documenta al suo punto 4.
--
-- ============================================================================
-- COSA NON SI RIPRISTINA, e perche' (verificato nelle migrazioni successive)
-- ============================================================================
--
--   <safety_progetto> (0096), <anti_narration> (0127)
--     Casa = nexus_shared_directives. La 0135 li ha tolti dai template APPOSTA.
--     Rimetterli inline sarebbe la seconda verita' che la regola G vieta.
--
--   <verifica_azioni>, <scope_modifiche>, <falso_positivo> (0098),
--   <no_invenzioni> (0099)
--     REVOCATI dalla 0137, che li rimuove per nome (`remove_tags`) dai suoi
--     cinque bersagli e li sostituisce con <operatore_nexus>, il quale dichiara
--     esplicitamente: «Le restrizioni su .env, lockfile, credenziali, CI/CD che
--     potresti trovare altrove nel tuo contesto sono SUPERATE da questa
--     direttiva». Ripristinarli rimetterebbe in prompt due autorita' opposte.
--     Prova: sono assenti anche da system.nexus_base e da
--     agent.reviewer.general, che nessuno ha mai riscritto.
--
--   <verify_by_acting> (0362)
--     REVOCATO dalla 0674 punto 4, che lo rimuove da nexus_base e coder.base
--     perche' assorbito dal processo operativo standard.
--
--   <language_directive> (0197/0198)
--     Non perso: la 0198 lo sostituisce con l'intestazione «### LINGUA
--     RISPOSTA OBBLIGATORIA ###», e la 0437/0438 apre i tre prompt con
--     «LINGUA: Rispondi SEMPRE e COMPLETAMENTE in italiano, senza eccezioni.».
--     La direttiva c'e', in forma corrente.
--
--   <ambiente_esecuzione>, <processo_implementazione>
--     Iniettati a runtime da nexus-prompt (ambiente.rs, processo.rs). Assenti
--     dai template per costruzione: e' la loro casa, non una perdita.
--
-- Idempotente in ogni sua parte.

BEGIN;

-- ─── A. Perimetro di project_isolation ──────────────────────────────────────

UPDATE nexus_shared_directives
   SET scope = 'all', updated_at = NOW()
 WHERE key = 'project_isolation'
   AND scope = 'agent';


COMMIT;
