"use client";

// KnowledgeWorkspace — scope-agnostic. Layout 3 colonne (tree | main | rail),
// 4 tab nel main (edit/graph/triples/history). Si appoggia esclusivamente
// agli endpoint /api/wiki/* (ADR 0017 v2 fase 7).
//
// Stesso componente, props diverse:
//   <KnowledgeWorkspace scope="meta" />
//   <KnowledgeWorkspace scope="project" projectId="..." />

import * as React from "react";
import {
  listDocs,
  getDoc,
  patchDoc,
  deleteDoc,
  getDocLinks,
  listRevisions,
  getRevision,
  diffRevisions,
  restoreRevision,
  type WikiDoc,
  type WikiRevision,
  type WikiScope,
  type WikiLinksResponse,
} from "../../lib/wiki-client";
import { buildTree, type WikiDocSummary } from "./wiki-scope";
import { WikiTreeNodeView } from "./wiki-tree";
import { WikiEditor } from "./wiki-editor";
import { MarkdownBlock } from "../chat/markdown-renderer";
import { useThemeColors } from "../../lib/theme";
import { useI18n } from "../../lib/i18n";
import { useGlobalDialog } from "../global-dialog-provider";
import { GraphFullPage } from "./graph-full-page";
import { TripleBrowser } from "./triple-browser";

interface Props {
  scope: WikiScope;
  projectId?: string;
  /**
   * Doc da pre-selezionare al mount (es. arrivando da `?doc=...`).
   * Usato quando il navigatore leggero in sidebar apre la KB full-page su un
   * documento specifico. Si applica una sola volta all'apertura.
   */
  initialDocId?: string;
}

type TabKey = "edit" | "graph" | "triples" | "history";

function docToSummary(d: WikiDoc): WikiDocSummary {
  return {
    id: d.id,
    title: d.title,
    path: d.vault_file_path ?? "",
    category: d.kind,
    tags: d.tags ?? [],
    autoGenerated: d.auto_generated,
    updatedAt: d.updated_at,
  };
}

export function KnowledgeWorkspace({ scope, projectId, initialDocId }: Props) {
  const tc = useThemeColors();
  const { t } = useI18n();
  const dialog = useGlobalDialog();

  // ─── Stato lista/selezione ──────────────────────────────────────────
  const [docs, setDocs] = React.useState<WikiDoc[]>([]);
  const [loadingList, setLoadingList] = React.useState(false);
  const [selectedId, setSelectedId] = React.useState<string | null>(initialDocId ?? null);
  const [selected, setSelected] = React.useState<WikiDoc | null>(null);
  const [links, setLinks] = React.useState<WikiLinksResponse | null>(null);
  const [loadingDetail, setLoadingDetail] = React.useState(false);
  const [error, setError] = React.useState<string | null>(null);
  const [filter, setFilter] = React.useState("");

  // ─── Stato editor ────────────────────────────────────────────────────
  const [tab, setTab] = React.useState<TabKey>("edit");
  const [draftTitle, setDraftTitle] = React.useState("");
  const [draftTags, setDraftTags] = React.useState("");
  const [draftBody, setDraftBody] = React.useState("");
  const [saving, setSaving] = React.useState(false);
  const [editMode, setEditMode] = React.useState(false);
  const [deleting, setDeleting] = React.useState(false);

  // ─── Stato history ───────────────────────────────────────────────────
  const [revisions, setRevisions] = React.useState<WikiRevision[]>([]);
  const [revFrom, setRevFrom] = React.useState<number | null>(null);
  const [revTo, setRevTo] = React.useState<number | null>(null);
  const [diff, setDiff] = React.useState<{ from: WikiRevision; to: WikiRevision } | null>(null);

  // ─── Layout responsive ───────────────────────────────────────────────
  const [viewportWidth, setViewportWidth] = React.useState<number>(
    typeof window !== "undefined" ? window.innerWidth : 1280,
  );
  React.useEffect(() => {
    if (typeof window === "undefined") return;
    const onResize = () => setViewportWidth(window.innerWidth);
    window.addEventListener("resize", onResize);
    return () => window.removeEventListener("resize", onResize);
  }, []);
  const isDesktop = viewportWidth >= 1280;
  const isTablet = viewportWidth >= 768 && viewportWidth < 1280;
  const isMobile = viewportWidth < 768;
  const [drawerTree, setDrawerTree] = React.useState(false);
  const [drawerRail, setDrawerRail] = React.useState(false);

  // ─── Carica lista ────────────────────────────────────────────────────
  const loadList = React.useCallback(async () => {
    setLoadingList(true);
    try {
      const r = await listDocs({ scope, project_id: projectId, limit: 1000 });
      setDocs(r.items);
    } catch (e: unknown) {
      setError(e instanceof Error ? e.message : String(e));
    } finally {
      setLoadingList(false);
    }
  }, [scope, projectId]);

  React.useEffect(() => {
    void loadList();
  }, [loadList]);

  // ─── Carica dettaglio quando cambia selezione ────────────────────────
  React.useEffect(() => {
    if (!selectedId) {
      setSelected(null);
      setLinks(null);
      return;
    }
    let cancelled = false;
    setLoadingDetail(true);
    Promise.all([getDoc(selectedId), getDocLinks(selectedId)])
      .then(([d, l]) => {
        if (cancelled) return;
        setSelected(d);
        setLinks(l);
        setDraftTitle(d.title);
        setDraftBody(d.body_md);
        setDraftTags((d.tags ?? []).join(", "));
        setEditMode(false);
      })
      .catch((e: unknown) => {
        if (!cancelled) setError(e instanceof Error ? e.message : String(e));
      })
      .finally(() => {
        if (!cancelled) setLoadingDetail(false);
      });
    return () => {
      cancelled = true;
    };
  }, [selectedId]);

  // ─── Albero filtrato ─────────────────────────────────────────────────
  const tree = React.useMemo(() => {
    const f = filter.trim().toLowerCase();
    const summaries = docs.map(docToSummary);
    const filtered = f
      ? summaries.filter(
          (s) =>
            s.title.toLowerCase().includes(f) || (s.path || "").toLowerCase().includes(f),
        )
      : summaries;
    return buildTree(filtered);
  }, [docs, filter]);

  // Mappa id -> titolo per la tab Concetti (TripleBrowser). Risolve l'UX
  // di "voglio leggere il titolo non l'UID" senza fetch extra: docs e' gia'
  // caricato dalla list.
  const docTitleMap = React.useMemo(() => {
    const m: Record<string, string> = {};
    for (const d of docs) m[d.id] = d.title;
    return m;
  }, [docs]);

  // ─── Salvataggio ─────────────────────────────────────────────────────
  const dirty =
    !!selected &&
    (draftBody !== selected.body_md ||
      draftTitle !== selected.title ||
      draftTags !== (selected.tags ?? []).join(", "));

  const onSave = React.useCallback(async () => {
    if (!selected || !dirty) return;
    setSaving(true);
    setError(null);
    try {
      const tags = draftTags
        .split(",")
        .map((s) => s.trim())
        .filter(Boolean);
      await patchDoc(selected.id, {
        title: draftTitle !== selected.title ? draftTitle : undefined,
        body_md: draftBody !== selected.body_md ? draftBody : undefined,
        tags: draftTags !== (selected.tags ?? []).join(", ") ? tags : undefined,
      });
      // Ricarica
      const d = await getDoc(selected.id);
      setSelected(d);
      setDraftTitle(d.title);
      setDraftBody(d.body_md);
      setDraftTags((d.tags ?? []).join(", "));
      void loadList();
      setEditMode(false);
    } catch (e: unknown) {
      setError(e instanceof Error ? e.message : String(e));
    } finally {
      setSaving(false);
    }
  }, [selected, dirty, draftTitle, draftBody, draftTags, loadList]);

  // ─── Eliminazione documento ─────────────────────────────────────────
  const onDelete = React.useCallback(async () => {
    if (!selected || deleting) return;
    const ok = await dialog.confirmDialog(
      t("wiki.editor.confirm_delete", { title: selected.title }),
    );
    if (!ok) return;
    const deletedId = selected.id;
    setDeleting(true);
    setError(null);
    try {
      await deleteDoc(deletedId);
      // Rimuovi dalla lista locale e deseleziona.
      setDocs((prev) => prev.filter((d) => d.id !== deletedId));
      setSelectedId(null);
      setSelected(null);
      setLinks(null);
      setTab("edit");
      setEditMode(false);
    } catch (e: unknown) {
      setError(e instanceof Error ? e.message : String(e));
    } finally {
      setDeleting(false);
    }
  }, [selected, deleting, dialog, t]);

  // Ctrl+S → save
  React.useEffect(() => {
    const onKey = (e: KeyboardEvent) => {
      if ((e.ctrlKey || e.metaKey) && e.key === "s" && editMode) {
        e.preventDefault();
        void onSave();
      }
    };
    window.addEventListener("keydown", onKey);
    return () => window.removeEventListener("keydown", onKey);
  }, [onSave, editMode]);

  // ─── History loaders ─────────────────────────────────────────────────
  const loadHistory = React.useCallback(async () => {
    if (!selected) return;
    try {
      const r = await listRevisions(selected.id);
      setRevisions(r.items);
      if (r.items.length >= 2) {
        setRevFrom(r.items[1].version_no);
        setRevTo(r.items[0].version_no);
      } else if (r.items.length === 1) {
        setRevFrom(r.items[0].version_no);
        setRevTo(r.items[0].version_no);
      }
    } catch (e: unknown) {
      setError(e instanceof Error ? e.message : String(e));
    }
  }, [selected]);

  React.useEffect(() => {
    if (tab === "history" && selected) void loadHistory();
  }, [tab, selected, loadHistory]);

  const compareRevisions = async () => {
    if (!selected || revFrom == null || revTo == null) return;
    try {
      const d = await diffRevisions(selected.id, revFrom, revTo);
      setDiff(d);
    } catch (e: unknown) {
      // Fallback: carica le due singole
      try {
        const [from, to] = await Promise.all([
          getRevision(selected.id, revFrom),
          getRevision(selected.id, revTo),
        ]);
        setDiff({ from, to });
      } catch {
        setError(e instanceof Error ? e.message : String(e));
      }
    }
  };

  const doRestore = async (version: number) => {
    if (!selected) return;
    const ok = await dialog.confirmDialog(
      t("wiki.history.confirm_restore", { v: String(version) }),
    );
    if (!ok) return;
    try {
      await restoreRevision(selected.id, version);
      const d = await getDoc(selected.id);
      setSelected(d);
      setDraftBody(d.body_md);
      setDraftTitle(d.title);
      setDraftTags((d.tags ?? []).join(", "));
      await loadHistory();
      setTab("edit");
    } catch (e: unknown) {
      setError(e instanceof Error ? e.message : String(e));
    }
  };

  // ─── Wikilink ────────────────────────────────────────────────────────
  const onWikiLink = React.useCallback(
    (target: string) => {
      const t0 = target.toLowerCase();
      const match = docs.find(
        (d) =>
          d.title.toLowerCase() === t0 ||
          d.slug.toLowerCase() === t0 ||
          (d.vault_file_path || "").toLowerCase().endsWith(`/${t0}.md`),
      );
      if (match) setSelectedId(match.id);
    },
    [docs],
  );

  // ─── Render ──────────────────────────────────────────────────────────
  // Larghezze pannelli (tree sinistro + rail destro): default sensati per
  // breakpoint, override utente persistito in localStorage. Min 160px (tree)
  // / 220px (rail) per restare usabili; max 720px per non comprimere il main.
  const DEFAULT_TREE = isDesktop ? 250 : isTablet ? 220 : 280;
  const DEFAULT_RAIL = 300;
  const PANE_MIN_TREE = 160;
  const PANE_MIN_RAIL = 220;
  const PANE_MAX = 720;

  const [treeWidth, setTreeWidth] = React.useState<number>(() => {
    if (typeof window === "undefined") return DEFAULT_TREE;
    const raw = window.localStorage.getItem("nexus.wiki.tree.width");
    const n = raw ? parseInt(raw, 10) : NaN;
    return Number.isFinite(n) && n >= PANE_MIN_TREE && n <= PANE_MAX ? n : DEFAULT_TREE;
  });
  const [railWidth, setRailWidth] = React.useState<number>(() => {
    if (typeof window === "undefined") return DEFAULT_RAIL;
    const raw = window.localStorage.getItem("nexus.wiki.rail.width");
    const n = raw ? parseInt(raw, 10) : NaN;
    return Number.isFinite(n) && n >= PANE_MIN_RAIL && n <= PANE_MAX ? n : DEFAULT_RAIL;
  });
  React.useEffect(() => {
    if (typeof window === "undefined") return;
    window.localStorage.setItem("nexus.wiki.tree.width", String(treeWidth));
  }, [treeWidth]);
  React.useEffect(() => {
    if (typeof window === "undefined") return;
    window.localStorage.setItem("nexus.wiki.rail.width", String(railWidth));
  }, [railWidth]);

  /** Drag handler riusabile per i divisori dei pannelli. `dir` definisce
   *  se il pannello cresce verso destra (tree) o verso sinistra (rail). */
  const startPaneDrag = React.useCallback(
    (
      ev: React.MouseEvent,
      current: number,
      setter: (n: number) => void,
      dir: "right" | "left",
      min: number,
    ) => {
      ev.preventDefault();
      const startX = ev.clientX;
      const startW = current;
      const move = (e: MouseEvent) => {
        const delta = e.clientX - startX;
        const next = dir === "right" ? startW + delta : startW - delta;
        setter(Math.max(min, Math.min(PANE_MAX, next)));
      };
      const up = () => {
        window.removeEventListener("mousemove", move);
        window.removeEventListener("mouseup", up);
        document.body.style.cursor = "";
        document.body.style.userSelect = "";
      };
      window.addEventListener("mousemove", move);
      window.addEventListener("mouseup", up);
      document.body.style.cursor = "col-resize";
      // Evita selezione testo accidentale durante il drag.
      document.body.style.userSelect = "none";
    },
    [PANE_MAX],
  );

  const treeColumn = (
    <aside
      style={{
        // flex 0 + width fissa (non shrinkare), cosi' la larghezza driven da
        // state non viene compressa dal flex layout quando il main e' grande.
        flex: "0 0 auto",
        width: isMobile ? "100%" : treeWidth,
        minWidth: 0,
        // borderRight rimosso su desktop: il PaneResizer (6px col-resize)
        // funge da bordo. Su mobile/tablet (drawer) lo manteniamo.
        borderRight: isMobile ? undefined : isTablet ? `1px solid ${tc.border}` : undefined,
        background: tc.bgCard,
        display: "flex",
        flexDirection: "column",
        height: "100%",
      }}
    >
      <div style={{ padding: "10px 12px", borderBottom: `1px solid ${tc.border}` }}>
        <input
          value={filter}
          onChange={(e) => setFilter(e.target.value)}
          placeholder={t("wiki.tree.filter")}
          style={{
            width: "100%",
            padding: "5px 8px",
            background: tc.bgInput,
            border: `1px solid ${tc.border}`,
            color: tc.text,
            borderRadius: 4,
            fontSize: 12,
            boxSizing: "border-box",
          }}
        />
        <div style={{ fontSize: 11, color: tc.textSecondary, marginTop: 6 }}>
          {docs.length} {t("wiki.tree.docs")}
        </div>
      </div>
      <div style={{ flex: 1, overflowY: "auto", padding: "6px 0", minHeight: 0 }}>
        {loadingList ? (
          <div style={{ padding: 12, color: tc.textSecondary, fontSize: 12 }}>
            {t("wiki.loading")}
          </div>
        ) : (
          <WikiTreeNodeView
            node={tree}
            depth={0}
            selectedId={selectedId}
            onSelect={(id) => {
              setSelectedId(id);
              if (isMobile) setDrawerTree(false);
            }}
            defaultOpen
          />
        )}
      </div>
    </aside>
  );

  const rail = (
    <aside
      style={{
        // flex 0 + width fissa, vedi commento in treeColumn.
        flex: "0 0 auto",
        width: isMobile ? "100%" : railWidth,
        minWidth: 0,
        // borderLeft rimosso su desktop: il PaneResizer e' il bordo. Sui
        // drawer (mobile) lo manteniamo.
        borderLeft: undefined,
        background: tc.bgCard,
        padding: "12px 14px",
        overflowY: "auto",
        fontSize: 12,
        height: "100%",
      }}
    >
      {!selected ? (
        <div style={{ color: tc.textSecondary, fontStyle: "italic" }}>
          {t("wiki.rail.no_selection")}
        </div>
      ) : (
        <>
          <RailSection title={t("wiki.rail.metadata")}>
            <Field label={t("wiki.metadata.kind")} value={selected.kind} tc={tc} />
            <Field
              label={t("wiki.metadata.scope")}
              value={`${selected.scope}${selected.project_id ? ` (${selected.project_id.slice(0, 8)})` : ""}`}
              tc={tc}
            />
            <Field
              label={t("wiki.metadata.version")}
              value={String(selected.current_version)}
              tc={tc}
            />
            <Field
              label={t("wiki.metadata.edit_lock")}
              value={selected.edit_lock}
              tc={tc}
            />
            {selected.auto_generated && (
              <div
                style={{
                  padding: "2px 8px",
                  background: tc.bgInput,
                  border: `1px solid ${tc.border}`,
                  borderRadius: 10,
                  fontSize: 10,
                  display: "inline-block",
                  marginTop: 4,
                }}
              >
                {t("wiki.metadata.auto_generated")}
              </div>
            )}
          </RailSection>

          <RailSection title={t("wiki.rail.tags") + ` (${selected.tags?.length ?? 0})`}>
            {(selected.tags ?? []).length === 0 && (
              <div style={{ color: tc.textSecondary, fontStyle: "italic" }}>
                {t("wiki.rail.no_tags")}
              </div>
            )}
            <div style={{ display: "flex", gap: 4, flexWrap: "wrap" }}>
              {(selected.tags ?? []).map((tag) => (
                <span
                  key={tag}
                  style={{
                    padding: "1px 8px",
                    background: tc.accent + "20",
                    color: tc.accent,
                    borderRadius: 10,
                    fontSize: 11,
                  }}
                >
                  #{tag}
                </span>
              ))}
            </div>
          </RailSection>

          <RailSection title={t("wiki.rail.backlinks") + ` (${links?.inbound?.length ?? 0})`}>
            {(links?.inbound ?? []).length === 0 && (
              <div style={{ color: tc.textSecondary, fontStyle: "italic" }}>
                {t("wiki.rail.none")}
              </div>
            )}
            {(links?.inbound ?? []).map((l, i) => (
              <button
                key={i}
                type="button"
                onClick={() => setSelectedId(l.from_doc.id)}
                style={linkBtnStyle(tc)}
                title={l.rel_type}
              >
                {l.from_doc.title}
              </button>
            ))}
          </RailSection>

          <RailSection title={t("wiki.rail.outgoing") + ` (${links?.outbound?.length ?? 0})`}>
            {(links?.outbound ?? []).length === 0 && (
              <div style={{ color: tc.textSecondary, fontStyle: "italic" }}>
                {t("wiki.rail.none")}
              </div>
            )}
            {(links?.outbound ?? []).map((l, i) => (
              <button
                key={i}
                type="button"
                onClick={() => setSelectedId(l.to_doc.id)}
                style={linkBtnStyle(tc)}
                title={l.rel_type}
              >
                {l.to_doc.title}
              </button>
            ))}
          </RailSection>
        </>
      )}
    </aside>
  );

  const mainContent = (
    <main
      style={{
        flex: 1,
        minWidth: 0,
        display: "flex",
        flexDirection: "column",
        height: "100%",
      }}
    >
      {/* Header con tab */}
      <div
        style={{
          padding: "8px 12px",
          borderBottom: `1px solid ${tc.border}`,
          background: tc.bgCard,
          display: "flex",
          gap: 6,
          alignItems: "center",
          flexWrap: "wrap",
        }}
      >
        {(isTablet || isMobile) && (
          <button
            type="button"
            onClick={() => setDrawerTree(true)}
            style={iconBtn(tc)}
            aria-label="tree"
          >
            ☰
          </button>
        )}
        {(["edit", "graph", "triples", "history"] as TabKey[]).map((k) => (
          <button
            key={k}
            type="button"
            onClick={() => setTab(k)}
            disabled={(k === "history" || k === "edit") && !selected}
            style={{
              padding: "5px 12px",
              background: tab === k ? tc.accent : "transparent",
              color: tab === k ? "#fff" : tc.text,
              border: `1px solid ${tab === k ? tc.accent : tc.border}`,
              borderRadius: 4,
              cursor: "pointer",
              fontSize: 12,
              fontWeight: 600,
              opacity: (k === "history" || k === "edit") && !selected ? 0.4 : 1,
            }}
          >
            {t(`wiki.tabs.${k}` as never) || k}
          </button>
        ))}
        <div style={{ flex: 1, minWidth: 0 }} />
        {selected && tab === "edit" && (
          <>
            {dirty && (
              <span style={{ fontSize: 11, color: tc.warning ?? "#f59e0b" }}>
                {t("wiki.editor.unsaved")}
              </span>
            )}
            {editMode ? (
              <>
                <button
                  type="button"
                  onClick={onSave}
                  disabled={!dirty || saving}
                  style={primaryBtn(tc, !dirty || saving)}
                >
                  {saving ? t("wiki.editor.saving") : t("wiki.editor.save")}
                </button>
                <button
                  type="button"
                  onClick={() => {
                    if (selected) {
                      setDraftBody(selected.body_md);
                      setDraftTitle(selected.title);
                      setDraftTags((selected.tags ?? []).join(", "));
                    }
                    setEditMode(false);
                  }}
                  style={secondaryBtn(tc)}
                >
                  {t("wiki.editor.cancel")}
                </button>
              </>
            ) : (
              <button type="button" onClick={() => setEditMode(true)} style={secondaryBtn(tc)}>
                {t("wiki.editor.edit")}
              </button>
            )}
            <button
              type="button"
              onClick={onDelete}
              disabled={deleting}
              style={dangerBtn(tc, deleting)}
              title={t("wiki.editor.delete")}
            >
              {deleting ? t("wiki.editor.deleting") : t("wiki.editor.delete")}
            </button>
          </>
        )}
        {(isTablet || isMobile) && (
          <button
            type="button"
            onClick={() => setDrawerRail(true)}
            style={iconBtn(tc)}
            aria-label="rail"
          >
            ☷
          </button>
        )}
      </div>

      {error && (
        <div
          style={{
            padding: "6px 14px",
            color: tc.error,
            fontSize: 12,
            borderBottom: `1px solid ${tc.border}`,
          }}
        >
          {error}{" "}
          <button
            onClick={() => setError(null)}
            style={{
              background: "transparent",
              border: "none",
              color: tc.accent,
              cursor: "pointer",
              fontSize: 11,
            }}
          >
            ✕
          </button>
        </div>
      )}

      {/* Body */}
      <section style={{ flex: 1, overflow: "hidden", minHeight: 0, display: "flex" }}>
        {tab === "edit" &&
          (selected ? (
            editMode ? (
              <WikiEditor
                draftTitle={draftTitle}
                setDraftTitle={setDraftTitle}
                draftTags={draftTags}
                setDraftTags={setDraftTags}
                draftBody={draftBody}
                setDraftBody={setDraftBody}
                onWikiLink={onWikiLink}
              />
            ) : (
              <div
                style={{
                  flex: 1,
                  overflowY: "auto",
                  padding: "16px 24px",
                  minWidth: 0,
                }}
              >
                {loadingDetail ? (
                  <div style={{ color: tc.textSecondary }}>{t("wiki.loading")}</div>
                ) : (
                  <>
                    <h1 style={{ margin: "0 0 8px", fontSize: 24, fontWeight: 700 }}>
                      {selected.title}
                    </h1>
                    <div
                      style={{
                        fontSize: 11,
                        color: tc.textSecondary,
                        marginBottom: 16,
                        display: "flex",
                        gap: 12,
                        flexWrap: "wrap",
                      }}
                    >
                      <span>
                        {t("wiki.metadata.kind")}: {selected.kind}
                      </span>
                      <span>
                        {t("wiki.metadata.updated_at")}:{" "}
                        {new Date(selected.updated_at).toLocaleString()}
                      </span>
                      <span>v{selected.current_version}</span>
                    </div>
                    <MarkdownBlock
                      content={selected.body_md}
                      skipNormalize
                      enableHeadingAnchors
                      slugPrefix="wiki-"
                      onWikiLink={onWikiLink}
                    />
                  </>
                )}
              </div>
            )
          ) : (
            <EmptyHint text={t("wiki.empty.select_doc")} tc={tc} />
          ))}

        {tab === "graph" && (
          <GraphFullPage scope={scope} projectId={projectId} onOpenDoc={(id) => {
            setSelectedId(id);
            setTab("edit");
          }} />
        )}

        {tab === "triples" && (
          <TripleBrowser
            scope={scope}
            projectId={projectId}
            // Mappa id -> titolo: la prima colonna mostra il titolo del
            // documento sorgente invece dell'UID (richiesta UX).
            docTitles={docTitleMap}
            onOpenDoc={(id) => {
              setSelectedId(id);
              setTab("edit");
            }}
          />
        )}

        {tab === "history" && selected && (
          <HistoryView
            revisions={revisions}
            revFrom={revFrom}
            revTo={revTo}
            diff={diff}
            setRevFrom={setRevFrom}
            setRevTo={setRevTo}
            onCompare={compareRevisions}
            onRestore={doRestore}
            tc={tc}
            t={t}
          />
        )}
      </section>
    </main>
  );

  return (
    <div
      style={{
        flex: 1,
        display: "flex",
        height: "100%",
        background: tc.bg,
        color: tc.text,
        overflow: "hidden",
        border: `1px solid ${tc.border}`,
        borderRadius: 6,
        minWidth: 0,
        minHeight: 0,
      }}
    >
      {isDesktop && treeColumn}
      {isDesktop && (
        <PaneResizer
          tc={tc}
          onMouseDown={(e) =>
            startPaneDrag(e, treeWidth, setTreeWidth, "right", PANE_MIN_TREE)
          }
          title="Trascina per ridimensionare la sidebar"
        />
      )}
      {isTablet && treeColumn}
      {mainContent}
      {/* La rail destra (metadata/tag/backlink del documento) ha senso solo
       *  quando si lavora su UN documento (tab edit/history). Per i tab globali
       *  (triples / graph) la nascondiamo cosi' la tabella/grafo usa tutto lo
       *  spazio rimanente (richiesta UX: "la lista deve occupare tutto lo
       *  spazio"). */}
      {isDesktop && tab !== "triples" && tab !== "graph" && (
        <PaneResizer
          tc={tc}
          onMouseDown={(e) =>
            startPaneDrag(e, railWidth, setRailWidth, "left", PANE_MIN_RAIL)
          }
          title="Trascina per ridimensionare il pannello dettagli"
        />
      )}
      {isDesktop && tab !== "triples" && tab !== "graph" && rail}

      {/* Drawer mobile / tablet */}
      {(isMobile || isTablet) && drawerTree && (
        <Drawer side="left" onClose={() => setDrawerTree(false)} tc={tc}>
          {treeColumn}
        </Drawer>
      )}
      {!isDesktop && drawerRail && (
        <Drawer side="right" onClose={() => setDrawerRail(false)} tc={tc}>
          {rail}
        </Drawer>
      )}
    </div>
  );
}

// ─────────────────────── Helper subcomponents ───────────────────────────

type ThemeColors = ReturnType<typeof useThemeColors>;
type Translator = ReturnType<typeof useI18n>["t"];

/** Divisore verticale draggabile tra due pannelli del layout (tree | main | rail).
 *  Larghezza 6px con indicatore visivo (border laterale) + hit area allargata
 *  via padding implicito; cursor col-resize. Il drag handler vero e' iniettato
 *  dal genitore via `onMouseDown` cosi' lo stato delle larghezze resta li'
 *  (single source of truth + persistenza localStorage). */
function PaneResizer({
  tc,
  onMouseDown,
  title,
}: {
  tc: ThemeColors;
  onMouseDown: (ev: React.MouseEvent) => void;
  title?: string;
}) {
  return (
    <div
      role="separator"
      aria-orientation="vertical"
      title={title}
      onMouseDown={onMouseDown}
      style={{
        flex: "0 0 auto",
        width: 6,
        height: "100%",
        cursor: "col-resize",
        // Indicatore visivo del divisore: barra sottile centrata del colore
        // del border. Hover non e' inline (no JS), ma l'utente trova il
        // divisore grazie al cursor + al colore del bordo gia' presente.
        background: tc.border,
        userSelect: "none",
      }}
    />
  );
}

function RailSection({ title, children }: { title: string; children: React.ReactNode }) {
  const tc = useThemeColors();
  return (
    <div style={{ marginBottom: 16 }}>
      <div style={{ fontWeight: 700, marginBottom: 6, fontSize: 11, color: tc.textSecondary, textTransform: "uppercase", letterSpacing: "0.05em" }}>
        {title}
      </div>
      {children}
    </div>
  );
}

function Field({ label, value, tc }: { label: string; value: string; tc: ThemeColors }) {
  return (
    <div style={{ display: "flex", gap: 6, fontSize: 12, marginBottom: 2 }}>
      <span style={{ color: tc.textSecondary, minWidth: 70 }}>{label}:</span>
      <span style={{ color: tc.text, fontFamily: "monospace", fontSize: 11 }}>{value}</span>
    </div>
  );
}

function linkBtnStyle(tc: ThemeColors): React.CSSProperties {
  return {
    display: "block",
    width: "100%",
    textAlign: "left",
    background: "none",
    border: "none",
    color: tc.accent,
    cursor: "pointer",
    padding: "2px 0",
    fontSize: 12,
    textDecoration: "underline",
  };
}

function primaryBtn(tc: ThemeColors, disabled: boolean): React.CSSProperties {
  return {
    padding: "5px 12px",
    background: disabled ? tc.bgInput : tc.accent,
    color: disabled ? tc.textSecondary : "#fff",
    border: "none",
    borderRadius: 4,
    cursor: disabled ? "not-allowed" : "pointer",
    fontSize: 12,
    fontWeight: 600,
    opacity: disabled ? 0.6 : 1,
  };
}

function secondaryBtn(tc: ThemeColors): React.CSSProperties {
  return {
    padding: "5px 12px",
    background: tc.bgInput,
    color: tc.text,
    border: `1px solid ${tc.border}`,
    borderRadius: 4,
    cursor: "pointer",
    fontSize: 12,
  };
}

function dangerBtn(tc: ThemeColors, disabled: boolean): React.CSSProperties {
  return {
    padding: "5px 12px",
    background: "transparent",
    color: tc.error,
    border: `1px solid ${tc.error}`,
    borderRadius: 4,
    cursor: disabled ? "not-allowed" : "pointer",
    fontSize: 12,
    fontWeight: 600,
    opacity: disabled ? 0.6 : 1,
  };
}

function iconBtn(tc: ThemeColors): React.CSSProperties {
  return {
    width: 30,
    height: 30,
    background: tc.bgInput,
    color: tc.text,
    border: `1px solid ${tc.border}`,
    borderRadius: 4,
    cursor: "pointer",
    display: "grid",
    placeItems: "center",
    fontSize: 14,
  };
}

function EmptyHint({ text, tc }: { text: string; tc: ThemeColors }) {
  return (
    <div
      style={{
        flex: 1,
        display: "grid",
        placeItems: "center",
        color: tc.textSecondary,
        padding: 32,
        fontSize: 13,
      }}
    >
      {text}
    </div>
  );
}

function Drawer({
  side,
  onClose,
  children,
  tc,
}: {
  side: "left" | "right";
  onClose: () => void;
  children: React.ReactNode;
  tc: ThemeColors;
}) {
  return (
    <div
      role="dialog"
      aria-modal="true"
      onClick={onClose}
      style={{
        position: "fixed",
        inset: 0,
        background: "rgba(0,0,0,0.45)",
        zIndex: 50,
        display: "flex",
        justifyContent: side === "left" ? "flex-start" : "flex-end",
      }}
    >
      <div
        onClick={(e) => e.stopPropagation()}
        style={{
          width: 320,
          maxWidth: "90vw",
          height: "100%",
          background: tc.bgSidebar ?? tc.bg,
          boxShadow: "0 12px 40px rgba(0,0,0,0.35)",
          display: "flex",
          flexDirection: "column",
        }}
      >
        {children}
      </div>
    </div>
  );
}

function HistoryView({
  revisions,
  revFrom,
  revTo,
  diff,
  setRevFrom,
  setRevTo,
  onCompare,
  onRestore,
  tc,
  t,
}: {
  revisions: WikiRevision[];
  revFrom: number | null;
  revTo: number | null;
  diff: { from: WikiRevision; to: WikiRevision } | null;
  setRevFrom: (n: number) => void;
  setRevTo: (n: number) => void;
  onCompare: () => void;
  onRestore: (v: number) => void;
  tc: ThemeColors;
  t: Translator;
}) {
  return (
    <div style={{ flex: 1, overflow: "auto", padding: 16, minWidth: 0 }}>
      <div style={{ display: "flex", gap: 16, flexWrap: "wrap" }}>
        {/* Tabella */}
        <div style={{ flex: 1, minWidth: 320 }}>
          <h3 style={{ marginTop: 0, fontSize: 14 }}>{t("wiki.history.revisions")}</h3>
          <table
            style={{
              width: "100%",
              borderCollapse: "collapse",
              fontSize: 12,
              color: tc.text,
            }}
          >
            <thead>
              <tr style={{ borderBottom: `1px solid ${tc.border}`, textAlign: "left" }}>
                <th style={{ padding: 6 }}>v</th>
                <th style={{ padding: 6 }}>{t("wiki.history.source")}</th>
                <th style={{ padding: 6 }}>{t("wiki.history.author")}</th>
                <th style={{ padding: 6 }}>{t("wiki.history.created")}</th>
                <th style={{ padding: 6 }}></th>
              </tr>
            </thead>
            <tbody>
              {revisions.length === 0 && (
                <tr>
                  <td colSpan={5} style={{ padding: 12, color: tc.textSecondary }}>
                    {t("wiki.history.empty")}
                  </td>
                </tr>
              )}
              {revisions.map((r) => (
                <tr key={r.version_no} style={{ borderBottom: `1px solid ${tc.border}` }}>
                  <td style={{ padding: 6 }}>
                    <label style={{ display: "flex", alignItems: "center", gap: 6 }}>
                      <input
                        type="radio"
                        name="revFrom"
                        checked={revFrom === r.version_no}
                        onChange={() => setRevFrom(r.version_no)}
                      />
                      <input
                        type="radio"
                        name="revTo"
                        checked={revTo === r.version_no}
                        onChange={() => setRevTo(r.version_no)}
                      />
                      <span>v{r.version_no}</span>
                    </label>
                  </td>
                  <td style={{ padding: 6 }}>{r.source}</td>
                  <td style={{ padding: 6 }}>{r.author ?? "-"}</td>
                  <td style={{ padding: 6 }}>{new Date(r.created_at).toLocaleString()}</td>
                  <td style={{ padding: 6 }}>
                    <button
                      type="button"
                      onClick={() => onRestore(r.version_no)}
                      style={secondaryBtn(tc)}
                    >
                      {t("wiki.history.restore")}
                    </button>
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
          <button
            type="button"
            onClick={onCompare}
            disabled={revFrom == null || revTo == null}
            style={{
              ...primaryBtn(tc, revFrom == null || revTo == null),
              marginTop: 10,
            }}
          >
            {t("wiki.history.compare")}
          </button>
        </div>

        {/* Diff testuale semplice */}
        {diff && (
          <div style={{ flex: 2, minWidth: 320 }}>
            <h3 style={{ marginTop: 0, fontSize: 14 }}>
              v{diff.from.version_no} → v{diff.to.version_no}
            </h3>
            <SimpleDiff a={diff.from.body_md} b={diff.to.body_md} tc={tc} />
          </div>
        )}
      </div>
    </div>
  );
}

function SimpleDiff({ a, b, tc }: { a: string; b: string; tc: ThemeColors }) {
  const aLines = a.split("\n");
  const bLines = b.split("\n");
  const aSet = new Set(aLines);
  const bSet = new Set(bLines);
  const rows: Array<{ kind: "add" | "del" | "ctx"; text: string }> = [];
  // Linee rimosse (in a, non in b)
  for (const line of aLines) {
    if (!bSet.has(line)) rows.push({ kind: "del", text: line });
  }
  // Linee aggiunte (in b, non in a)
  for (const line of bLines) {
    if (!aSet.has(line)) rows.push({ kind: "add", text: line });
  }
  return (
    <pre
      style={{
        background: tc.bgInput,
        padding: 10,
        borderRadius: 4,
        border: `1px solid ${tc.border}`,
        fontSize: 11.5,
        fontFamily: "monospace",
        overflow: "auto",
        maxHeight: 600,
        whiteSpace: "pre-wrap",
      }}
    >
      {rows.length === 0 ? (
        <span style={{ color: tc.textSecondary }}>(nessuna differenza)</span>
      ) : (
        rows.map((r, i) => (
          <div
            key={i}
            style={{
              color:
                r.kind === "add"
                  ? "#16a34a"
                  : r.kind === "del"
                    ? "#dc2626"
                    : tc.text,
            }}
          >
            {r.kind === "add" ? "+ " : r.kind === "del" ? "- " : "  "}
            {r.text || " "}
          </div>
        ))
      )}
    </pre>
  );
}
