// Adapter scope per la wiki Nexus. Normalizza le due API (meta-docs e
// knowledge per-progetto) su un'interfaccia comune `WikiScope`, cosi' tutti
// i componenti wiki sono scritti UNA volta sola e servono entrambi gli scope.

import {
  listMetaDocs,
  getMetaDoc,
  patchMetaDoc,
  listMetaDocRevisions,
  getMetaDocRevision,
  restoreMetaDocRevision,
  listKnowledgeNotes,
  getKnowledgeNote,
  patchKnowledgeNote,
  listKnowledgeNoteRevisions,
  getKnowledgeNoteRevision,
  restoreKnowledgeNoteRevision,
  type MetaDocSummary,
  type MetaDocDetail,
  type KnowledgeNote,
  type WikiRevision,
} from "../../lib/api-client";

export interface WikiDocSummary {
  id: string;
  title: string;
  /** Path nel vault (`architecture/crates-rust.md` o `.nexus/knowledge/notes/...`). Puo' essere vuoto. */
  path: string;
  /** Categoria: per meta = kind, per progetto = intent (o kind se manca). */
  category: string;
  tags: string[];
  autoGenerated: boolean;
  updatedAt: string;
}

export interface WikiBacklink {
  id: string | null;
  title: string;
  relType?: string;
}

export interface WikiDocDetail extends WikiDocSummary {
  bodyMd: string;
  createdAt: string;
  outgoing: WikiBacklink[];
  incoming: WikiBacklink[];
  status?: string;
  manuallyEdited?: boolean;
  editLock?: string;
  currentVersion?: number;
}

export interface WikiScope {
  kind: "meta" | "project";
  projectId?: string;
  list(params?: { q?: string; limit?: number; offset?: number }): Promise<{
    items: WikiDocSummary[];
    total: number;
  }>;
  get(id: string): Promise<WikiDocDetail>;
  patch(id: string, body: { title?: string; body_md?: string; tags?: string[] }): Promise<{
    ok: boolean;
    version: number;
  }>;
  listRevisions(id: string): Promise<WikiRevision[]>;
  getRevision(id: string, version: number): Promise<WikiRevision>;
  restoreRevision(id: string, version: number): Promise<{ version: number }>;
  /** Per il grafo Cytoscape (KnowledgeGraph). */
  graphMode: "meta" | "project";
}

// ─────────────────────────────── META ────────────────────────────────────

function metaSummary(s: MetaDocSummary): WikiDocSummary {
  return {
    id: s.id,
    title: s.title,
    path: s.vault_file_path ?? "",
    category: s.kind,
    tags: s.tags ?? [],
    autoGenerated: s.auto_generated,
    updatedAt: s.updated_at,
  };
}

function metaDetail(d: MetaDocDetail): WikiDocDetail {
  return {
    ...metaSummary(d),
    bodyMd: d.body_md,
    createdAt: d.created_at,
    outgoing: (d.outgoing_links ?? []).map((l) => ({
      id: l.to_or_from_id ?? null,
      title: l.title,
      relType: l.rel_type,
    })),
    incoming: (d.incoming_links ?? []).map((l) => ({
      id: l.to_or_from_id ?? null,
      title: l.title,
      relType: l.rel_type,
    })),
  };
}

export function makeMetaScope(): WikiScope {
  return {
    kind: "meta",
    graphMode: "meta",
    async list(params) {
      const res = await listMetaDocs({
        q: params?.q,
        limit: params?.limit ?? 500,
        offset: params?.offset ?? 0,
      });
      return { items: res.items.map(metaSummary), total: res.total };
    },
    async get(id) {
      const d = await getMetaDoc(id);
      return metaDetail(d);
    },
    async patch(id, body) {
      const r = await patchMetaDoc(id, body);
      return { ok: r.ok, version: r.version };
    },
    async listRevisions(id) {
      const r = await listMetaDocRevisions(id);
      return r.items;
    },
    async getRevision(id, version) {
      return getMetaDocRevision(id, version);
    },
    async restoreRevision(id, version) {
      const r = await restoreMetaDocRevision(id, version);
      return { version: r.version };
    },
  };
}

// ─────────────────────────────── PROGETTO ─────────────────────────────────

function projectSummary(n: KnowledgeNote): WikiDocSummary {
  return {
    id: n.id,
    title: n.title,
    path: n.vaultFilePath ?? "",
    category: (n.intent ?? "other") as string,
    tags: n.tags ?? [],
    // Una nota e' "manuale" se non nasce da un messaggio chat ne' da un run.
    autoGenerated: !!(n.sourceMessageId || n.sourceRunId),
    updatedAt: n.updatedAt,
  };
}

function projectDetail(n: KnowledgeNote): WikiDocDetail {
  return {
    ...projectSummary(n),
    bodyMd: n.bodyMd ?? "",
    createdAt: n.createdAt,
    status: n.status,
    outgoing: (n.outgoing ?? []).map((l) => ({
      id: l.toNoteId ?? null,
      title: l.toTitle ?? "",
      relType: l.relType,
    })),
    incoming: (n.backlinks ?? []).map((l) => ({
      id: l.fromNoteId ?? null,
      title: l.fromTitle ?? "",
      relType: l.relType,
    })),
  };
}

export function makeProjectScope(projectId: string): WikiScope {
  return {
    kind: "project",
    projectId,
    graphMode: "project",
    async list(params) {
      const res = await listKnowledgeNotes(projectId, {
        q: params?.q,
        limit: params?.limit ?? 500,
        offset: params?.offset ?? 0,
      });
      return {
        items: res.notes.map(projectSummary),
        total: res.total,
      };
    },
    async get(id) {
      const n = await getKnowledgeNote(projectId, id);
      return projectDetail(n);
    },
    async patch(id, body) {
      const r = await patchKnowledgeNote(projectId, id, body);
      return { ok: r.ok, version: (r as { version?: number }).version ?? 0 };
    },
    async listRevisions(id) {
      const r = await listKnowledgeNoteRevisions(projectId, id);
      return r.items;
    },
    async getRevision(id, version) {
      return getKnowledgeNoteRevision(projectId, id, version);
    },
    async restoreRevision(id, version) {
      const r = await restoreKnowledgeNoteRevision(projectId, id, version);
      return { version: r.version };
    },
  };
}

// ─────────────────────────── Albero (path-based) ──────────────────────────

export interface WikiTreeNode {
  /** Segmento path corrente (es. "architecture", "adr-001.md"). */
  name: string;
  /** Path completo dalla radice fino a questo nodo. */
  path: string;
  /** Bambini cartelle/file. */
  children: WikiTreeNode[];
  /** Documento associato a questa foglia (presente solo per le foglie). */
  doc?: WikiDocSummary;
}

/** Costruisce l'albero gerarchico a partire dai vault_file_path dei documenti. */
export function buildTree(items: WikiDocSummary[]): WikiTreeNode {
  const root: WikiTreeNode = { name: "", path: "", children: [] };
  // Doc senza path: raggruppali sotto "(senza-path)"
  const orphans: WikiDocSummary[] = [];
  for (const d of items) {
    if (!d.path) {
      orphans.push(d);
      continue;
    }
    const parts = d.path.split("/").filter(Boolean);
    let cur = root;
    parts.forEach((part, idx) => {
      const isLeaf = idx === parts.length - 1;
      let child = cur.children.find((c) => c.name === part);
      if (!child) {
        child = {
          name: part,
          path: parts.slice(0, idx + 1).join("/"),
          children: [],
        };
        cur.children.push(child);
      }
      if (isLeaf) child.doc = d;
      cur = child;
    });
  }
  if (orphans.length > 0) {
    const bucket: WikiTreeNode = { name: "(senza path)", path: "__no_path__", children: [] };
    for (const o of orphans) {
      bucket.children.push({ name: o.title, path: `__no_path__/${o.id}`, children: [], doc: o });
    }
    root.children.push(bucket);
  }
  sortTree(root);
  return root;
}

function sortTree(node: WikiTreeNode) {
  node.children.sort((a, b) => {
    // Cartelle prima dei file
    const aDir = a.children.length > 0 && !a.doc ? 0 : 1;
    const bDir = b.children.length > 0 && !b.doc ? 0 : 1;
    if (aDir !== bDir) return aDir - bDir;
    return a.name.localeCompare(b.name);
  });
  for (const c of node.children) sortTree(c);
}
