// Catalogo curato di server MCP per lo sviluppo software.
// Usato dal pannello "Catalogo" in McpConnectors.

type CatalogCategory =
  | "databases"
  | "version-control"
  | "cloud"
  | "dev-tools"
  | "ai-ml"
  | "productivity"
  | "search"
  | "filesystem"
  | "communication"
  | "monitoring";

export interface CatalogEntry {
  id: string;
  name: string;
  description: string;
  category: CatalogCategory;
  icon: string;
  transport: "http" | "stdio";
  url?: string;
  command?: string;
  args?: string[];
  requiredEnvVars?: string[];
  optionalEnvVars?: string[];
  tags?: string[];
  docsUrl?: string;
  official?: boolean;
}

export const MCP_CATALOG: CatalogEntry[] = [
  // ── Filesystem ────────────────────────────────────────────────────────────
  {
    id: "filesystem-local",
    name: "Filesystem",
    description: "Leggi, scrivi e cerca file e directory sul filesystem del server con controllo accessi configurabile.",
    category: "filesystem",
    icon: "📁",
    transport: "stdio",
    command: "npx",
    args: ["-y", "@modelcontextprotocol/server-filesystem", "/"],
    tags: ["file", "directory", "read", "write", "search"],
    docsUrl: "https://github.com/modelcontextprotocol/servers/tree/main/src/filesystem",
    official: true,
  },
  {
    id: "memory",
    name: "Memory (Knowledge Graph)",
    description: "Memoria persistente per gli agenti tramite knowledge graph locale — salva entità, relazioni e osservazioni tra sessioni.",
    category: "filesystem",
    icon: "🧠",
    transport: "stdio",
    command: "npx",
    args: ["-y", "@modelcontextprotocol/server-memory"],
    tags: ["memory", "knowledge", "graph", "persistence", "entities"],
    docsUrl: "https://github.com/modelcontextprotocol/servers/tree/main/src/memory",
    official: true,
  },
  {
    id: "sequential-thinking",
    name: "Sequential Thinking",
    description: "Ragionamento strutturato step-by-step — decompone problemi complessi, rivede conclusioni, esplora branch alternativi.",
    category: "filesystem",
    icon: "🤔",
    transport: "stdio",
    command: "npx",
    args: ["-y", "@modelcontextprotocol/server-sequential-thinking"],
    tags: ["reasoning", "thinking", "planning", "analysis"],
    docsUrl: "https://github.com/modelcontextprotocol/servers/tree/main/src/sequentialthinking",
    official: true,
  },
  {
    id: "everything",
    name: "Everything (Demo)",
    description: "Server di riferimento e test con prompts, resources e tools — utile per verificare l'integrazione MCP.",
    category: "filesystem",
    icon: "🔮",
    transport: "stdio",
    command: "npx",
    args: ["-y", "@modelcontextprotocol/server-everything"],
    tags: ["test", "demo", "reference", "debug"],
    docsUrl: "https://github.com/modelcontextprotocol/servers/tree/main/src/everything",
    official: true,
  },

  // ── Version Control ───────────────────────────────────────────────────────
  {
    id: "github-http",
    name: "GitHub (HTTP)",
    description: "Accesso a repository GitHub tramite API HTTP — gestisci PR, Issues, Commits, Branches, Actions e Code Security.",
    category: "version-control",
    icon: "🐙",
    transport: "http",
    url: "https://api.githubcopilot.com/mcp",
    requiredEnvVars: ["GITHUB_TOKEN"],
    tags: ["github", "git", "pr", "pull request", "issue", "commit", "branch", "actions"],
    docsUrl: "https://github.com/github/github-mcp-server",
    official: true,
  },
  {
    id: "github-stdio",
    name: "GitHub (stdio)",
    description: "Versione stdio del server GitHub MCP — ideale per ambienti senza accesso HTTP diretto all'API Copilot.",
    category: "version-control",
    icon: "🐙",
    transport: "stdio",
    command: "npx",
    args: ["-y", "@modelcontextprotocol/server-github"],
    requiredEnvVars: ["GITHUB_PERSONAL_ACCESS_TOKEN"],
    tags: ["github", "git", "pr", "issue", "repository"],
    docsUrl: "https://github.com/modelcontextprotocol/servers-archived/tree/main/src/github",
  },
  {
    id: "gitlab",
    name: "GitLab",
    description: "Integrazione con GitLab — accedi a repository, merge request, issues, pipeline CI/CD e gruppi.",
    category: "version-control",
    icon: "🦊",
    transport: "stdio",
    command: "npx",
    args: ["-y", "@modelcontextprotocol/server-gitlab"],
    requiredEnvVars: ["GITLAB_PERSONAL_ACCESS_TOKEN"],
    optionalEnvVars: ["GITLAB_API_URL"],
    tags: ["gitlab", "git", "merge request", "ci", "pipeline"],
    docsUrl: "https://github.com/modelcontextprotocol/servers-archived/tree/main/src/gitlab",
  },

  // ── Databases ─────────────────────────────────────────────────────────────
  {
    id: "postgres",
    name: "PostgreSQL",
    description: "Esegui query SQL read-only su database PostgreSQL — esplora schema, tabelle e dati con sicurezza.",
    category: "databases",
    icon: "🐘",
    transport: "stdio",
    command: "npx",
    args: ["-y", "@modelcontextprotocol/server-postgres", "postgresql://localhost/mydb"],
    tags: ["postgres", "postgresql", "sql", "database", "query"],
    docsUrl: "https://github.com/modelcontextprotocol/servers-archived/tree/main/src/postgres",
    official: true,
  },
  {
    id: "sqlite",
    name: "SQLite",
    description: "Query e analisi su database SQLite locali — utile per file .db del progetto, dati di test, storage locale.",
    category: "databases",
    icon: "🗄️",
    transport: "stdio",
    command: "npx",
    args: ["-y", "@modelcontextprotocol/server-sqlite"],
    tags: ["sqlite", "sql", "database", "local", "file"],
    docsUrl: "https://github.com/modelcontextprotocol/servers-archived/tree/main/src/sqlite",
    official: true,
  },
  {
    id: "mysql",
    name: "MySQL",
    description: "Connessione a database MySQL — esegui query, esplora schema e analizza dati in modo sicuro.",
    category: "databases",
    icon: "🐬",
    transport: "stdio",
    command: "npx",
    args: ["-y", "@benborla29/mcp-server-mysql"],
    requiredEnvVars: ["MYSQL_HOST", "MYSQL_USER", "MYSQL_PASS", "MYSQL_DB"],
    tags: ["mysql", "sql", "database", "query"],
  },
  {
    id: "mongodb",
    name: "MongoDB",
    description: "Accesso a database MongoDB — esegui query, esplora collection e aggregazioni su dati NoSQL.",
    category: "databases",
    icon: "🍃",
    transport: "stdio",
    command: "npx",
    args: ["-y", "@pash1986/mcp-server-mongodb"],
    requiredEnvVars: ["MONGODB_URI"],
    tags: ["mongodb", "nosql", "database", "document"],
  },
  {
    id: "redis",
    name: "Redis",
    description: "Interagisci con Redis — GET/SET chiavi, esplora strutture dati, pubblica su canali, analizza performance.",
    category: "databases",
    icon: "🔴",
    transport: "stdio",
    command: "npx",
    args: ["-y", "@modelcontextprotocol/server-redis"],
    requiredEnvVars: ["REDIS_URL"],
    tags: ["redis", "cache", "key-value", "pubsub", "queue"],
  },
  {
    id: "supabase",
    name: "Supabase",
    description: "Backend-as-a-Service con PostgreSQL, Auth, Storage e Realtime — gestisci tabelle, edge functions e policy RLS.",
    category: "databases",
    icon: "⚡",
    transport: "stdio",
    command: "npx",
    args: ["-y", "@supabase/mcp-server-supabase"],
    requiredEnvVars: ["SUPABASE_URL", "SUPABASE_SERVICE_ROLE_KEY"],
    tags: ["supabase", "postgres", "auth", "storage", "realtime", "baas"],
    docsUrl: "https://github.com/supabase-community/supabase-mcp",
  },
  {
    id: "neon",
    name: "Neon Serverless",
    description: "Database PostgreSQL serverless con branching — crea branch, esegui query, gestisci progetti Neon.",
    category: "databases",
    icon: "🔷",
    transport: "stdio",
    command: "npx",
    args: ["-y", "@neondatabase/mcp-server-neon"],
    requiredEnvVars: ["NEON_API_KEY"],
    tags: ["neon", "postgres", "serverless", "branching", "cloud"],
    docsUrl: "https://github.com/neondatabase/mcp-server-neon",
  },

  // ── Cloud & API ───────────────────────────────────────────────────────────
  {
    id: "cloudflare",
    name: "Cloudflare",
    description: "Gestisci zone DNS, Workers, R2, D1, KV e Pages su Cloudflare — deploy e configurazione da chat.",
    category: "cloud",
    icon: "🌥️",
    transport: "stdio",
    command: "npx",
    args: ["-y", "@cloudflare/mcp-server-cloudflare"],
    requiredEnvVars: ["CLOUDFLARE_API_TOKEN", "CLOUDFLARE_ACCOUNT_ID"],
    tags: ["cloudflare", "dns", "workers", "cdn", "r2", "kv", "d1"],
    docsUrl: "https://github.com/cloudflare/mcp-server-cloudflare",
    official: false,
  },
  {
    id: "vercel",
    name: "Vercel",
    description: "Deploy, gestione progetti e domini su Vercel — crea deployment, gestisci env vars e controlla build logs.",
    category: "cloud",
    icon: "▲",
    transport: "stdio",
    command: "npx",
    args: ["-y", "@vercel/mcp-adapter"],
    requiredEnvVars: ["VERCEL_TOKEN"],
    tags: ["vercel", "deploy", "nextjs", "edge", "serverless"],
    docsUrl: "https://github.com/vercel/mcp-adapter",
  },
  {
    id: "stripe",
    name: "Stripe",
    description: "Integrazione Stripe — gestisci pagamenti, clienti, abbonamenti, prodotti e report finanziari.",
    category: "cloud",
    icon: "💳",
    transport: "stdio",
    command: "npx",
    args: ["-y", "@stripe/agent-toolkit"],
    requiredEnvVars: ["STRIPE_SECRET_KEY"],
    tags: ["stripe", "payments", "billing", "subscription", "checkout"],
    docsUrl: "https://github.com/stripe/agent-toolkit",
  },
  {
    id: "aws-kb",
    name: "AWS Knowledge Base",
    description: "Recupera contenuti da AWS Bedrock Knowledge Base con RAG — query semantiche su dati aziendali.",
    category: "cloud",
    icon: "☁️",
    transport: "stdio",
    command: "npx",
    args: ["-y", "@modelcontextprotocol/server-aws-kb-retrieval"],
    requiredEnvVars: ["AWS_ACCESS_KEY_ID", "AWS_SECRET_ACCESS_KEY", "AWS_REGION"],
    optionalEnvVars: ["AWS_SESSION_TOKEN"],
    tags: ["aws", "bedrock", "rag", "knowledge base", "s3"],
    official: true,
  },
  {
    id: "twilio",
    name: "Twilio",
    description: "SMS, chiamate, WhatsApp e video tramite Twilio — invia messaggi e gestisci numeri di telefono.",
    category: "cloud",
    icon: "📞",
    transport: "stdio",
    command: "npx",
    args: ["-y", "@twilio-alpha/mcp"],
    requiredEnvVars: ["TWILIO_ACCOUNT_SID", "TWILIO_AUTH_TOKEN"],
    tags: ["twilio", "sms", "phone", "whatsapp", "voice", "messaging"],
  },
  {
    id: "sendgrid",
    name: "SendGrid",
    description: "Invia email transazionali e di marketing tramite SendGrid — gestisci template, contatti e statistiche.",
    category: "cloud",
    icon: "📧",
    transport: "stdio",
    command: "npx",
    args: ["-y", "@sendgrid/mcp"],
    requiredEnvVars: ["SENDGRID_API_KEY"],
    tags: ["sendgrid", "email", "smtp", "marketing", "transactional"],
  },
  {
    id: "digitalocean",
    name: "DigitalOcean",
    description: "Gestisci Droplet, Kubernetes, Spaces e database su DigitalOcean — provisioning e monitoring dell'infrastruttura.",
    category: "cloud",
    icon: "🐟",
    transport: "http",
    url: "https://mcp.digitalocean.com/mcp",
    requiredEnvVars: ["DO_API_KEY"],
    tags: ["digitalocean", "vps", "kubernetes", "droplet", "spaces", "cloud"],
  },

  // ── Dev Tools ─────────────────────────────────────────────────────────────
  {
    id: "brave-search",
    name: "Brave Search",
    description: "Ricerca web in tempo reale con Brave Search API — risultati privacy-focused senza tracking.",
    category: "dev-tools",
    icon: "🦁",
    transport: "stdio",
    command: "npx",
    args: ["-y", "@modelcontextprotocol/server-brave-search"],
    requiredEnvVars: ["BRAVE_API_KEY"],
    tags: ["search", "web", "brave", "privacy"],
    docsUrl: "https://github.com/modelcontextprotocol/servers-archived/tree/main/src/brave-search",
    official: true,
  },
  {
    id: "web-fetch",
    name: "Web Fetch",
    description: "Scarica pagine web e convertile in markdown ottimizzato per LLM — leggi documentazione, articoli e README.",
    category: "dev-tools",
    icon: "🌐",
    transport: "stdio",
    command: "uvx",
    args: ["mcp-server-fetch"],
    tags: ["fetch", "http", "web", "scraping", "markdown", "documentation"],
    docsUrl: "https://github.com/modelcontextprotocol/servers/tree/main/src/fetch",
    official: true,
  },
  {
    id: "playwright",
    name: "Playwright (Browser)",
    description: "Automazione browser Chromium/Firefox/WebKit — naviga pagine, clicca, compila form, fa screenshot e testa UI.",
    category: "dev-tools",
    icon: "🎭",
    transport: "stdio",
    command: "npx",
    args: ["@playwright/mcp@latest"],
    tags: ["playwright", "browser", "automation", "testing", "screenshot", "e2e"],
    docsUrl: "https://github.com/microsoft/playwright-mcp",
  },
  {
    id: "puppeteer",
    name: "Puppeteer",
    description: "Automazione browser Chromium con Puppeteer — scraping, screenshot, PDF, interazione con pagine SPA.",
    category: "dev-tools",
    icon: "🤖",
    transport: "stdio",
    command: "npx",
    args: ["-y", "@modelcontextprotocol/server-puppeteer"],
    tags: ["puppeteer", "browser", "chrome", "scraping", "screenshot", "pdf"],
    docsUrl: "https://github.com/modelcontextprotocol/servers-archived/tree/main/src/puppeteer",
    official: true,
  },
  {
    id: "docker",
    name: "Docker",
    description: "Gestisci container Docker — elenca, avvia, ferma container, ispeziona logs e gestisci immagini e volumi.",
    category: "dev-tools",
    icon: "🐋",
    transport: "stdio",
    command: "npx",
    args: ["-y", "@ckreiling/mcp-server-docker"],
    tags: ["docker", "container", "image", "compose", "devops"],
  },
  {
    id: "kubernetes",
    name: "Kubernetes",
    description: "Interagisci con cluster Kubernetes — gestisci pod, deployment, service, configmap e namespace.",
    category: "dev-tools",
    icon: "☸️",
    transport: "stdio",
    command: "npx",
    args: ["-y", "@strowk/mcp-k8s"],
    optionalEnvVars: ["KUBECONFIG"],
    tags: ["kubernetes", "k8s", "pod", "deployment", "devops", "cluster"],
  },
  {
    id: "sentry",
    name: "Sentry",
    description: "Accedi a errori, eventi e performance da Sentry — analizza stack trace e identifica issue in produzione.",
    category: "dev-tools",
    icon: "🐛",
    transport: "stdio",
    command: "npx",
    args: ["-y", "@sentry/mcp-server"],
    requiredEnvVars: ["SENTRY_AUTH_TOKEN"],
    tags: ["sentry", "error", "monitoring", "stack trace", "performance"],
  },

  // ── Search ────────────────────────────────────────────────────────────────
  {
    id: "tavily",
    name: "Tavily Search",
    description: "Motore di ricerca AI-optimized per agenti — risultati arricchiti con estratti, immagini e fonti affidabili.",
    category: "search",
    icon: "🔎",
    transport: "stdio",
    command: "npx",
    args: ["-y", "tavily-mcp"],
    requiredEnvVars: ["TAVILY_API_KEY"],
    tags: ["tavily", "search", "ai", "research", "web"],
    docsUrl: "https://github.com/tavily-ai/tavily-mcp",
  },
  {
    id: "exa",
    name: "Exa Search",
    description: "Ricerca semantica avanzata sul web con Exa — comprende il significato delle query, non solo le parole chiave.",
    category: "search",
    icon: "🔬",
    transport: "stdio",
    command: "npx",
    args: ["-y", "exa-mcp-server"],
    requiredEnvVars: ["EXA_API_KEY"],
    tags: ["exa", "search", "semantic", "neural", "research"],
  },
  {
    id: "perplexity",
    name: "Perplexity",
    description: "AI search con Perplexity — risposte accurate con fonti citate, aggiornate in tempo reale.",
    category: "search",
    icon: "💡",
    transport: "stdio",
    command: "npx",
    args: ["-y", "@ppl-ai/mcp"],
    requiredEnvVars: ["PERPLEXITY_API_KEY"],
    tags: ["perplexity", "search", "ai", "research", "citations"],
  },
  {
    id: "google-search",
    name: "Google Custom Search",
    description: "Ricerca tramite Google Custom Search API — accedi ai risultati Google programmaticamente.",
    category: "search",
    icon: "🌍",
    transport: "stdio",
    command: "npx",
    args: ["-y", "@adenot/mcp-google-search"],
    requiredEnvVars: ["GOOGLE_API_KEY", "GOOGLE_SEARCH_ENGINE_ID"],
    tags: ["google", "search", "web", "custom search"],
  },

  // ── Productivity ──────────────────────────────────────────────────────────
  {
    id: "google-drive",
    name: "Google Drive",
    description: "Accedi e cerca file su Google Drive — leggi documenti, fogli, presentazioni e file condivisi.",
    category: "productivity",
    icon: "📂",
    transport: "stdio",
    command: "npx",
    args: ["-y", "@modelcontextprotocol/server-gdrive"],
    requiredEnvVars: ["GOOGLE_CLIENT_ID", "GOOGLE_CLIENT_SECRET"],
    tags: ["google", "drive", "docs", "sheets", "slides", "storage"],
    docsUrl: "https://github.com/modelcontextprotocol/servers-archived/tree/main/src/gdrive",
    official: true,
  },
  {
    id: "google-maps",
    name: "Google Maps",
    description: "Geocodifica, ricerca luoghi, calcola percorsi e ottieni informazioni geografiche tramite Google Maps API.",
    category: "productivity",
    icon: "🗺️",
    transport: "stdio",
    command: "npx",
    args: ["-y", "@modelcontextprotocol/server-google-maps"],
    requiredEnvVars: ["GOOGLE_MAPS_API_KEY"],
    tags: ["google", "maps", "geocoding", "directions", "places", "geo"],
    docsUrl: "https://github.com/modelcontextprotocol/servers-archived/tree/main/src/google-maps",
    official: true,
  },
  {
    id: "slack",
    name: "Slack",
    description: "Interagisci con Slack — leggi messaggi, invia notifiche, cerca canali e gestisci il workspace.",
    category: "productivity",
    icon: "💬",
    transport: "stdio",
    command: "npx",
    args: ["-y", "@modelcontextprotocol/server-slack"],
    requiredEnvVars: ["SLACK_BOT_TOKEN", "SLACK_TEAM_ID"],
    tags: ["slack", "chat", "messaging", "team", "notification", "workspace"],
    docsUrl: "https://github.com/modelcontextprotocol/servers-archived/tree/main/src/slack",
    official: true,
  },
  {
    id: "notion",
    name: "Notion",
    description: "Accedi e modifica pagine, database e documenti Notion — integra la knowledge base aziendale nei tuoi agenti.",
    category: "productivity",
    icon: "📝",
    transport: "stdio",
    command: "npx",
    args: ["-y", "@modelcontextprotocol/server-notion"],
    requiredEnvVars: ["NOTION_API_KEY"],
    tags: ["notion", "wiki", "docs", "database", "knowledge base", "notes"],
  },
  {
    id: "linear",
    name: "Linear",
    description: "Gestisci issue, progetti e sprint su Linear — crea ticket, aggiorna stati e consulta la roadmap del team.",
    category: "productivity",
    icon: "📋",
    transport: "stdio",
    command: "npx",
    args: ["-y", "@linear/mcp-server"],
    requiredEnvVars: ["LINEAR_API_KEY"],
    tags: ["linear", "issue", "project management", "sprint", "ticket", "backlog"],
    docsUrl: "https://github.com/linear/linear-mcp",
  },

  // ── AI / ML ───────────────────────────────────────────────────────────────
  {
    id: "huggingface",
    name: "Hugging Face",
    description: "Accedi a modelli, dataset e spazi su Hugging Face — inferenza, fine-tuning info e hub API.",
    category: "ai-ml",
    icon: "🤗",
    transport: "stdio",
    command: "npx",
    args: ["-y", "@huggingface/mcp-server"],
    requiredEnvVars: ["HF_TOKEN"],
    tags: ["huggingface", "ml", "models", "dataset", "transformers", "inference"],
  },
  {
    id: "openai",
    name: "OpenAI API",
    description: "Chiama direttamente l'API OpenAI — generazione testo, embeddings, immagini DALL-E e moderazione contenuti.",
    category: "ai-ml",
    icon: "🧬",
    transport: "stdio",
    command: "npx",
    args: ["-y", "@modelcontextprotocol/server-openai"],
    requiredEnvVars: ["OPENAI_API_KEY"],
    tags: ["openai", "gpt", "chatgpt", "embeddings", "dalle", "whisper"],
  },
  {
    id: "stability-ai",
    name: "Stability AI",
    description: "Genera immagini con Stable Diffusion tramite Stability AI API — text-to-image, image-to-image e upscaling.",
    category: "ai-ml",
    icon: "🎨",
    transport: "stdio",
    command: "npx",
    args: ["-y", "@stability-ai/mcp"],
    requiredEnvVars: ["STABILITY_KEY"],
    tags: ["stability", "stable diffusion", "image generation", "ai art", "dalle"],
  },

  // ── Monitoring ────────────────────────────────────────────────────────────
  {
    id: "grafana",
    name: "Grafana",
    description: "Accedi a dashboard, alert e metriche su Grafana — interroga datasource, visualizza panel e analizza trend.",
    category: "monitoring",
    icon: "📊",
    transport: "stdio",
    command: "npx",
    args: ["-y", "@grafana/mcp-grafana"],
    requiredEnvVars: ["GRAFANA_URL", "GRAFANA_TOKEN"],
    tags: ["grafana", "metrics", "dashboard", "monitoring", "prometheus", "loki"],
    docsUrl: "https://github.com/grafana/mcp-grafana",
  },
  {
    id: "datadog",
    name: "Datadog",
    description: "Monitoring, APM e log su Datadog — interroga metriche, analizza trace e visualizza dashboard.",
    category: "monitoring",
    icon: "🐕",
    transport: "stdio",
    command: "npx",
    args: ["-y", "@datadog/mcp-server"],
    requiredEnvVars: ["DD_API_KEY", "DD_APP_KEY"],
    tags: ["datadog", "metrics", "apm", "logs", "monitoring", "traces"],
  },

  // ── Communication ─────────────────────────────────────────────────────────
  {
    id: "discord",
    name: "Discord",
    description: "Interagisci con server Discord — leggi messaggi, invia notifiche e gestisci canali tramite bot.",
    category: "communication",
    icon: "🎮",
    transport: "stdio",
    command: "npx",
    args: ["-y", "@discord/mcp"],
    requiredEnvVars: ["DISCORD_BOT_TOKEN"],
    tags: ["discord", "chat", "gaming", "community", "bot", "notification"],
  },
  {
    id: "telegram",
    name: "Telegram",
    description: "Invia messaggi e gestisci bot Telegram — notifiche, comandi e integrazione con gruppi e canali.",
    category: "communication",
    icon: "✈️",
    transport: "stdio",
    command: "npx",
    args: ["-y", "@tulabyte/mcp-telegram-server"],
    requiredEnvVars: ["TELEGRAM_BOT_TOKEN"],
    tags: ["telegram", "messaging", "bot", "notification", "chat"],
  },
  // ── Testing ──────────────────────────────────────────────────────────
  {
    id: "testsprite",
    name: "TestSprite",
    description:
      "Agente AI di testing autonomo — genera test plan, codice test (Playwright/Cypress) e li esegue in 10-20 minuti senza QA manuale. Supporta frontend UI e backend API.",
    category: "dev-tools",
    icon: "🧪",
    transport: "stdio",
    command: "npx",
    args: ["@testsprite/testsprite-mcp@latest"],
    requiredEnvVars: ["API_KEY"],
    tags: [
      "testing",
      "qa",
      "automation",
      "playwright",
      "cypress",
      "e2e",
      "frontend",
      "backend",
      "api-testing",
    ],
    docsUrl: "https://docs.testsprite.com/mcp/getting-started/installation",
  },
];
