//! Route admin (require admin role).
//!
//! Estratte da `main.rs` durante il refactor del god-file. Nessun
//! cambiamento di path, metodo HTTP, handler o middleware.

use crate::routes::prelude::*;
use crate::*;

pub fn merge(router: Router<AppState>, state: &AppState) -> Router<AppState> {
    router
        // Admin routes (require admin role)
        .route(
            "/api/admin/settings",
            get(settings::list_settings)
                .put(settings::bulk_update)
                .layer(axum_mw::from_fn_with_state(
                    state.clone(),
                    middleware::require_admin,
                )),
        )
        // Learned instructions (mig 0412): review umana delle regole distillate.
        .route(
            "/api/admin/learned-instructions",
            get(learned_instructions::list_learned_instructions).layer(
                axum_mw::from_fn_with_state(state.clone(), middleware::require_admin),
            ),
        )
        .route(
            "/api/admin/learned-instructions/distill",
            post(learned_instructions::distill_now).layer(axum_mw::from_fn_with_state(
                state.clone(),
                middleware::require_admin,
            )),
        )
        .route(
            "/api/admin/learned-instructions/:id",
            patch(learned_instructions::patch_learned_instruction).layer(
                axum_mw::from_fn_with_state(state.clone(), middleware::require_admin),
            ),
        )
        // Bug 7 fix: trigger manuale del worker model_catalog_sync.
        // POST /api/admin/catalog-sync -> esegue 1 tick subito e ritorna lo stats.
        // Utile per onboarding (popola subito catalog) e test E2E (no attesa interval).
        .route(
            "/api/admin/catalog-sync",
            axum::routing::post(
                |axum::extract::State(s): axum::extract::State<AppState>| async move {
                    match model_catalog_sync::trigger_sync_now(&s.db, Some(&s.orchestrator)).await {
                        Ok(summary) => {
                            axum::Json(serde_json::json!({"ok": true, "summary": summary}))
                        }
                        Err(e) => axum::Json(serde_json::json!({"ok": false, "error": e})),
                    }
                },
            )
            .layer(axum_mw::from_fn_with_state(
                state.clone(),
                middleware::require_admin,
            )),
        )
        .route(
            "/api/admin/fs/directories",
            get(settings::browse_directories).layer(axum_mw::from_fn_with_state(
                state.clone(),
                middleware::require_admin,
            )),
        )
        .route(
            "/api/admin/fs/directories/create",
            post(settings::create_directory).layer(axum_mw::from_fn_with_state(
                state.clone(),
                middleware::require_admin,
            )),
        )
        .route(
            "/api/admin/setting/:key",
            put(settings::update_setting).layer(axum_mw::from_fn_with_state(
                state.clone(),
                middleware::require_admin,
            )),
        )
        .route(
            "/api/admin/settings-by-category/:category",
            get(settings::list_by_category).layer(axum_mw::from_fn_with_state(
                state.clone(),
                middleware::require_admin,
            )),
        )
        .route(
            "/api/admin/settings-categories",
            get(settings::list_categories).layer(axum_mw::from_fn_with_state(
                state.clone(),
                middleware::require_admin,
            )),
        )
        .route(
            "/api/admin/billing/prices",
            get(billing::list_prices).post(billing::create_price).layer(
                axum_mw::from_fn_with_state(state.clone(), middleware::require_admin),
            ),
        )
        .route(
            "/api/admin/billing/prices/:id",
            put(billing::update_price).layer(axum_mw::from_fn_with_state(
                state.clone(),
                middleware::require_admin,
            )),
        )
        .route(
            "/api/admin/billing/quotas",
            get(billing::list_quotas).post(billing::create_quota).layer(
                axum_mw::from_fn_with_state(state.clone(), middleware::require_admin),
            ),
        )
        .route(
            "/api/admin/billing/quotas/:id",
            put(billing::update_quota).layer(axum_mw::from_fn_with_state(
                state.clone(),
                middleware::require_admin,
            )),
        )
        .route(
            "/api/admin/billing/usage",
            get(billing::admin_usage_report).layer(axum_mw::from_fn_with_state(
                state.clone(),
                middleware::require_admin,
            )),
        )
        // Admin — gestione profili di sistema
        .route(
            "/api/admin/profiles",
            get(profiles::admin_list_profiles)
                .post(profiles::admin_create_profile)
                .layer(axum_mw::from_fn_with_state(
                    state.clone(),
                    middleware::require_admin,
                )),
        )
        .route(
            "/api/admin/profiles/:id",
            put(profiles::admin_update_profile)
                .delete(profiles::admin_delete_profile)
                .layer(axum_mw::from_fn_with_state(
                    state.clone(),
                    middleware::require_admin,
                )),
        )
        // Associazione server MCP <-> profilo. Gli handler esistevano dalla
        // nascita ma le route NON erano mai state montate: la sezione MCP
        // della pagina /admin/profiles falliva in silenzio (bonifica dead
        // code 2026-06-11, il warning never-used ha rivelato il gap).
        .route(
            "/api/admin/profiles/:id/mcp-servers",
            get(profiles::admin_get_profile_mcp_servers)
                .put(profiles::admin_set_profile_mcp_servers)
                .layer(axum_mw::from_fn_with_state(
                    state.clone(),
                    middleware::require_admin,
                )),
        )
        .route(
            "/api/admin/global-mcp-servers",
            get(profiles::admin_list_global_mcp_servers).layer(axum_mw::from_fn_with_state(
                state.clone(),
                middleware::require_admin,
            )),
        )
        // Admin — profili custom degli utenti (read-only)
        .route(
            "/api/admin/user-profiles",
            get(profiles::admin_list_user_profiles).layer(axum_mw::from_fn_with_state(
                state.clone(),
                middleware::require_admin,
            )),
        )
        .route(
            "/api/admin/feedback/errors",
            get(chat_learning::admin_list_feedback_errors).layer(axum_mw::from_fn_with_state(
                state.clone(),
                middleware::require_admin,
            )),
        )
        .route(
            "/api/admin/feedback/:id/review",
            post(chat_learning::admin_review_feedback).layer(axum_mw::from_fn_with_state(
                state.clone(),
                middleware::require_admin,
            )),
        )
        // ─── Sudo Manager (ADR 0017 Livello 1) ───────────────────────────
        .route(
            "/api/admin/sudo/status",
            get(sudo_routes::admin_sudo_status).layer(axum_mw::from_fn_with_state(
                state.clone(),
                middleware::require_admin,
            )),
        )
        .route(
            "/api/admin/sudo/purposes",
            get(sudo_routes::admin_sudo_list_purposes)
                .post(sudo_routes::admin_sudo_create_purpose)
                .layer(axum_mw::from_fn_with_state(
                    state.clone(),
                    middleware::require_admin,
                )),
        )
        .route(
            "/api/admin/sudo/purposes/:id",
            axum::routing::patch(sudo_routes::admin_sudo_patch_purpose)
                .delete(sudo_routes::admin_sudo_delete_purpose)
                .layer(axum_mw::from_fn_with_state(
                    state.clone(),
                    middleware::require_admin,
                )),
        )
        .route(
            "/api/admin/sudo/execute",
            post(sudo_routes::admin_sudo_execute).layer(axum_mw::from_fn_with_state(
                state.clone(),
                middleware::require_admin,
            )),
        )
        .route(
            "/api/admin/sudo/audit",
            get(sudo_routes::admin_sudo_audit).layer(axum_mw::from_fn_with_state(
                state.clone(),
                middleware::require_admin,
            )),
        )
        .route(
            "/api/admin/learning/projects/:id/retrain-routing",
            post(chat_learning::admin_retrain_project_routing).layer(axum_mw::from_fn_with_state(
                state.clone(),
                middleware::require_admin,
            )),
        )
        .route(
            "/api/admin/learning/projects/:id/config",
            get(chat_learning::admin_get_project_learning_config)
                .put(chat_learning::admin_update_project_learning_config)
                .layer(axum_mw::from_fn_with_state(
                    state.clone(),
                    middleware::require_admin,
                )),
        )
        .route(
            "/api/admin/vector/compact",
            post(chat_learning::admin_run_vector_compaction).layer(axum_mw::from_fn_with_state(
                state.clone(),
                middleware::require_admin,
            )),
        )
        .route(
            "/api/admin/vector/compact/runs",
            get(chat_learning::admin_list_vector_compaction_runs).layer(
                axum_mw::from_fn_with_state(state.clone(), middleware::require_admin),
            ),
        )
        // Prompt corrections (prompt_corrections Qdrant + Postgres)
        .route(
            "/api/admin/prompt-corrections",
            get(chat_learning::admin_list_prompt_corrections)
                .post(chat_learning::admin_create_prompt_correction)
                .layer(axum_mw::from_fn_with_state(
                    state.clone(),
                    middleware::require_admin,
                )),
        )
        .route(
            "/api/admin/prompt-corrections/:id",
            delete(chat_learning::admin_delete_prompt_correction).layer(
                axum_mw::from_fn_with_state(state.clone(), middleware::require_admin),
            ),
        )
        // Long-running patterns CRUD
        .route(
            "/api/admin/long-running",
            get(long_running::list_patterns)
                .post(long_running::create_pattern)
                .layer(axum_mw::from_fn_with_state(
                    state.clone(),
                    middleware::require_admin,
                )),
        )
        .route(
            "/api/admin/long-running/:id",
            put(long_running::update_pattern)
                .delete(long_running::delete_pattern)
                .layer(axum_mw::from_fn_with_state(
                    state.clone(),
                    middleware::require_admin,
                )),
        )
        .route(
            "/api/admin/sync-model-catalog",
            post(models::sync_model_catalog).layer(axum_mw::from_fn_with_state(
                state.clone(),
                middleware::require_admin,
            )),
        )
        .route(
            "/api/admin/probe-models",
            post(models::probe_models_now).layer(axum_mw::from_fn_with_state(
                state.clone(),
                middleware::require_admin,
            )),
        )
        // Admin users management
        .route(
            "/api/admin/users",
            get(admin::users::list_users).layer(axum_mw::from_fn_with_state(
                state.clone(),
                middleware::require_admin,
            )),
        )
        .route(
            "/api/admin/users/search",
            get(admin::users::search_users).layer(axum_mw::from_fn_with_state(
                state.clone(),
                middleware::require_admin,
            )),
        )
        .route(
            "/api/admin/users/:user_id",
            get(admin::users::get_user)
                .put(admin::users::update_user)
                .delete(admin::users::delete_user)
                .layer(axum_mw::from_fn_with_state(
                    state.clone(),
                    middleware::require_admin,
                )),
        )
        .route(
            "/api/admin/users/:user_id/role",
            put(admin::users::update_user_role).layer(axum_mw::from_fn_with_state(
                state.clone(),
                middleware::require_admin,
            )),
        )
        // Admin projects management
        .route(
            "/api/admin/projects",
            get(admin::projects::list_all_projects).layer(axum_mw::from_fn_with_state(
                state.clone(),
                middleware::require_admin,
            )),
        )
        .route(
            "/api/admin/projects/port",
            post(admin::projects::port_projects).layer(axum_mw::from_fn_with_state(
                state.clone(),
                middleware::require_admin,
            )),
        )
        .route(
            "/api/admin/projects/:project_id/members",
            get(admin::projects::list_project_members)
                .post(admin::projects::add_project_member)
                .layer(axum_mw::from_fn_with_state(
                    state.clone(),
                    middleware::require_admin,
                )),
        )
        .route(
            "/api/admin/projects/:project_id/members/:user_id",
            put(admin::projects::update_project_member)
                .delete(admin::projects::remove_project_member)
                .layer(axum_mw::from_fn_with_state(
                    state.clone(),
                    middleware::require_admin,
                )),
        )
        // Environment status & fix
        .route(
            "/api/admin/environment/status",
            get(environment::get_environment_status).layer(axum_mw::from_fn_with_state(
                state.clone(),
                middleware::require_admin,
            )),
        )
        .route(
            "/api/admin/environment/fix",
            post(environment::fix_environment).layer(axum_mw::from_fn_with_state(
                state.clone(),
                middleware::require_admin,
            )),
        )
        .route(
            "/api/admin/qdrant-health",
            get(environment::qdrant_health_handler).layer(axum_mw::from_fn_with_state(
                state.clone(),
                middleware::require_admin,
            )),
        )
        .route(
            "/api/admin/watchdog-status",
            get(task_watchdog::watchdog_status_handler).layer(axum_mw::from_fn_with_state(
                state.clone(),
                middleware::require_admin,
            )),
        )
        .route(
            "/api/admin/embeddings/validate",
            post(environment::embeddings_validate_handler).layer(axum_mw::from_fn_with_state(
                state.clone(),
                middleware::require_admin,
            )),
        )
        .route(
            "/api/admin/embeddings/apply",
            post(environment::embeddings_apply_handler).layer(axum_mw::from_fn_with_state(
                state.clone(),
                middleware::require_admin,
            )),
        )
        // Admin — purpose models (nexus_purpose_model)
        .route(
            "/api/admin/routing/purpose-models",
            get(admin::routing::list_purpose_models).layer(axum_mw::from_fn_with_state(
                state.clone(),
                middleware::require_admin,
            )),
        )
        .route(
            "/api/admin/routing/purpose-model/:purpose",
            put(admin::routing::update_purpose_model).layer(axum_mw::from_fn_with_state(
                state.clone(),
                middleware::require_admin,
            )),
        )
        // Admin — provider registry (nexus_provider_registry) data-driven per la
        // dashboard: elenco provider + criterio attivazione + link billing.
        .route(
            "/api/admin/provider-registry",
            get(admin::providers::list_provider_registry).layer(axum_mw::from_fn_with_state(
                state.clone(),
                middleware::require_admin,
            )),
        )
        // Admin — modelli del catalog INCLUSI i disabilitati (per abilitarli).
        .route(
            "/api/admin/provider-models",
            get(admin::providers::list_provider_models).layer(axum_mw::from_fn_with_state(
                state.clone(),
                middleware::require_admin,
            )),
        )
        // Admin — abilita/disabilita un modello del catalog (ai_price_catalog).
        .route(
            "/api/admin/provider-models/enabled",
            put(admin::providers::set_model_enabled).layer(axum_mw::from_fn_with_state(
                state.clone(),
                middleware::require_admin,
            )),
        )
        .route(
            "/api/gateway/providers",
            get(environment::gateway_providers_handler).layer(axum_mw::from_fn_with_state(
                state.clone(),
                middleware::require_admin,
            )),
        )
        .route(
            "/api/gateway/reload",
            post(environment::gateway_reload_handler).layer(axum_mw::from_fn_with_state(
                state.clone(),
                middleware::require_admin,
            )),
        )
        // Retrocompatibilità: percorsi /api/admin/gateway/* per il frontend vecchio
        // (rimosso dopo che il frontend sarà stato ridistribuito con i nuovi percorsi)
        .route(
            "/api/admin/gateway/providers",
            get(environment::gateway_providers_handler).layer(axum_mw::from_fn_with_state(
                state.clone(),
                middleware::require_admin,
            )),
        )
        .route(
            "/api/admin/gateway/reload",
            post(environment::gateway_reload_handler).layer(axum_mw::from_fn_with_state(
                state.clone(),
                middleware::require_admin,
            )),
        )
        // Admin — gestione cooldown provider (lista + reset manuale)
        // NOTA: la route senza path parameter deve precedere quella con :name
        .route(
            "/api/admin/providers/cooldown",
            get(environment::admin_cooldown_list).layer(axum_mw::from_fn_with_state(
                state.clone(),
                middleware::require_admin,
            )),
        )
        .route(
            "/api/admin/providers/budget",
            get(environment::admin_providers_budget_list).layer(axum_mw::from_fn_with_state(
                state.clone(),
                middleware::require_admin,
            )),
        )
        .route(
            "/api/admin/routing-matrix/auto-promote-now",
            post(environment::admin_routing_matrix_auto_promote_now).layer(
                axum_mw::from_fn_with_state(state.clone(), middleware::require_admin),
            ),
        )
        .route(
            "/api/admin/providers/:name/reset-cooldown",
            post(environment::admin_reset_provider_cooldown).layer(axum_mw::from_fn_with_state(
                state.clone(),
                middleware::require_admin,
            )),
        )
        .route(
            "/api/admin/providers/:name/set-budget",
            post(environment::admin_set_provider_budget).layer(axum_mw::from_fn_with_state(
                state.clone(),
                middleware::require_admin,
            )),
        )
        .route(
            "/api/admin/providers/:name/recharge-budget",
            post(environment::admin_recharge_provider_budget).layer(axum_mw::from_fn_with_state(
                state.clone(),
                middleware::require_admin,
            )),
        )
        .route(
            "/api/models",
            get(models::list_models).layer(axum_mw::from_fn_with_state(
                state.clone(),
                middleware::require_auth,
            )),
        )
        .route(
            "/api/models/routing-preview",
            get(models::routing_preview).layer(axum_mw::from_fn_with_state(
                state.clone(),
                middleware::require_auth,
            )),
        )
        .route(
            "/api/billing/usage/me",
            get(billing::my_usage_report).layer(axum_mw::from_fn_with_state(
                state.clone(),
                middleware::require_auth,
            )),
        )
        .route(
            "/api/projects/:id/billing/usage",
            get(billing::project_usage_report).layer(axum_mw::from_fn_with_state(
                state.clone(),
                middleware::require_auth,
            )),
        )
        .route(
            "/api/billing/session-usage",
            get(billing::get_session_usage).layer(axum_mw::from_fn_with_state(
                state.clone(),
                middleware::require_auth,
            )),
        )
}
