//! Route dispatcher SSE, MCP connectors, profili, plugin manager.
//!
//! Estratte da `main.rs` durante il refactor del god-file. Nessun
//! cambiamento di path, metodo HTTP, handler o middleware.

use crate::routes::prelude::*;
use crate::*;

pub fn merge(router: Router<AppState>, state: &AppState) -> Router<AppState> {
    router
        // ── Dispatcher centrale: SSE stream + snapshot ──
        .route(
            "/api/projects/:id/event-stream",
            get(dispatcher_routes::event_stream).layer(axum_mw::from_fn_with_state(
                state.clone(),
                middleware::require_auth,
            )),
        )
        .route(
            "/api/projects/:id/snapshot",
            get(dispatcher_routes::project_snapshot).layer(axum_mw::from_fn_with_state(
                state.clone(),
                middleware::require_auth,
            )),
        )
        .route(
            "/api/projects/:id/dispatcher/test",
            post(dispatcher_routes::dispatcher_test).layer(axum_mw::from_fn_with_state(
                state.clone(),
                middleware::require_auth,
            )),
        )
        .route(
            "/api/projects/:id/run-configs/detect",
            get(project_workspace::detect_run_configs).layer(axum_mw::from_fn_with_state(
                state.clone(),
                middleware::require_auth,
            )),
        )
        .route(
            "/api/projects/:id/run-configs",
            get(project_workspace::get_run_configs)
                .post(project_workspace::create_run_config)
                .layer(axum_mw::from_fn_with_state(
                    state.clone(),
                    middleware::require_auth,
                )),
        )
        .route(
            "/api/projects/:id/run-configs/:config_id",
            put(project_workspace::update_run_config)
                .delete(project_workspace::delete_run_config)
                .layer(axum_mw::from_fn_with_state(
                    state.clone(),
                    middleware::require_auth,
                )),
        )
        .route(
            "/api/projects/:id/run-configs/:config_id/launch",
            post(project_workspace::launch_run_config).layer(axum_mw::from_fn_with_state(
                state.clone(),
                middleware::require_auth,
            )),
        )
        .route(
            "/api/projects/:id/git/status",
            get(project_git::git_status).layer(axum_mw::from_fn_with_state(
                state.clone(),
                middleware::require_auth,
            )),
        )
        .route(
            "/api/projects/:id/git/log",
            get(project_git::git_log).layer(axum_mw::from_fn_with_state(
                state.clone(),
                middleware::require_auth,
            )),
        )
        .route(
            "/api/projects/:id/git/diff",
            get(project_git::git_diff).layer(axum_mw::from_fn_with_state(
                state.clone(),
                middleware::require_auth,
            )),
        )
        .route(
            "/api/projects/:id/git/branches",
            get(project_git::git_branches).layer(axum_mw::from_fn_with_state(
                state.clone(),
                middleware::require_auth,
            )),
        )
        .route(
            "/api/projects/:id/git/stage",
            post(project_git::git_stage).layer(axum_mw::from_fn_with_state(
                state.clone(),
                middleware::require_auth,
            )),
        )
        .route(
            "/api/projects/:id/git/unstage",
            post(project_git::git_unstage).layer(axum_mw::from_fn_with_state(
                state.clone(),
                middleware::require_auth,
            )),
        )
        .route(
            "/api/projects/:id/git/commit",
            post(project_git::git_commit).layer(axum_mw::from_fn_with_state(
                state.clone(),
                middleware::require_auth,
            )),
        )
        .route(
            "/api/projects/:id/git/checkout",
            post(project_git::git_checkout).layer(axum_mw::from_fn_with_state(
                state.clone(),
                middleware::require_auth,
            )),
        )
        .route(
            "/api/projects/:id/git/branch",
            post(project_git::git_create_branch).layer(axum_mw::from_fn_with_state(
                state.clone(),
                middleware::require_auth,
            )),
        )
        .route(
            "/api/projects/:id/git/pull",
            post(project_git::git_pull).layer(axum_mw::from_fn_with_state(
                state.clone(),
                middleware::require_auth,
            )),
        )
        .route(
            "/api/projects/:id/git/push",
            post(project_git::git_push).layer(axum_mw::from_fn_with_state(
                state.clone(),
                middleware::require_auth,
            )),
        )
        .route(
            "/api/projects/:id/github/status",
            get(github::github_project_status).layer(axum_mw::from_fn_with_state(
                state.clone(),
                middleware::require_auth,
            )),
        )
        .route(
            "/api/projects/:id/github/repositories",
            get(github::github_list_repositories).layer(axum_mw::from_fn_with_state(
                state.clone(),
                middleware::require_auth,
            )),
        )
        .route(
            "/api/projects/:id/github/clone",
            post(github::github_clone_repository).layer(axum_mw::from_fn_with_state(
                state.clone(),
                middleware::require_auth,
            )),
        )
        .route(
            "/api/projects/:id/github/create-repo",
            post(github::github_create_repo).layer(axum_mw::from_fn_with_state(
                state.clone(),
                middleware::require_auth,
            )),
        )
        .route(
            "/api/projects/:id/github/publish",
            post(github::github_publish_project).layer(axum_mw::from_fn_with_state(
                state.clone(),
                middleware::require_auth,
            )),
        )
        .route(
            "/api/projects/:id/github/publish-branch",
            post(github::github_publish_branch).layer(axum_mw::from_fn_with_state(
                state.clone(),
                middleware::require_auth,
            )),
        )
        .route(
            "/api/projects/:id/github/pull-request",
            post(github::github_create_pull_request).layer(axum_mw::from_fn_with_state(
                state.clone(),
                middleware::require_auth,
            )),
        )
        // MCP Connectors (per-user)
        .route(
            "/api/mcp-servers",
            get(mcp_connectors::list_mcp_servers)
                .post(mcp_connectors::create_mcp_server)
                .layer(axum_mw::from_fn_with_state(
                    state.clone(),
                    middleware::require_auth,
                )),
        )
        .route(
            "/api/mcp-servers/:id",
            put(mcp_connectors::update_mcp_server)
                .delete(mcp_connectors::delete_mcp_server)
                .layer(axum_mw::from_fn_with_state(
                    state.clone(),
                    middleware::require_auth,
                )),
        )
        .route(
            "/api/mcp-servers/:id/toggle",
            put(mcp_connectors::toggle_mcp_server).layer(axum_mw::from_fn_with_state(
                state.clone(),
                middleware::require_auth,
            )),
        )
        .route(
            "/api/mcp-servers/:id/test",
            post(mcp_connectors::test_mcp_server).layer(axum_mw::from_fn_with_state(
                state.clone(),
                middleware::require_auth,
            )),
        )
        // Profili utente (GPT/Gem style)
        .route(
            "/api/profiles",
            get(profiles::list_profiles)
                .post(profiles::create_profile)
                .layer(axum_mw::from_fn_with_state(
                    state.clone(),
                    middleware::require_auth,
                )),
        )
        .route(
            "/api/profiles/:id",
            put(profiles::update_profile)
                .delete(profiles::delete_profile)
                .layer(axum_mw::from_fn_with_state(
                    state.clone(),
                    middleware::require_auth,
                )),
        )
        .route(
            "/api/profiles/:id/default",
            post(profiles::set_default_profile).layer(axum_mw::from_fn_with_state(
                state.clone(),
                middleware::require_auth,
            )),
        )
        .route(
            "/api/profiles/:id/fork",
            post(profiles::fork_profile).layer(axum_mw::from_fn_with_state(
                state.clone(),
                middleware::require_auth,
            )),
        )
        // Plugin Manager (MCP-first)
        .route(
            "/api/plugins/catalog",
            get(plugins::list_plugin_catalog).layer(axum_mw::from_fn_with_state(
                state.clone(),
                middleware::require_auth,
            )),
        )
        .route(
            "/api/plugins/installed",
            get(plugins::list_installed_plugins).layer(axum_mw::from_fn_with_state(
                state.clone(),
                middleware::require_auth,
            )),
        )
        .route(
            "/api/plugins/figma/oauth/status",
            get(plugins::get_figma_oauth_status).layer(axum_mw::from_fn_with_state(
                state.clone(),
                middleware::require_auth,
            )),
        )
        .route(
            "/api/plugins/figma/oauth/connect",
            post(plugins::start_figma_oauth).layer(axum_mw::from_fn_with_state(
                state.clone(),
                middleware::require_auth,
            )),
        )
        .route(
            "/api/plugins/install",
            post(plugins::install_plugin).layer(axum_mw::from_fn_with_state(
                state.clone(),
                middleware::require_auth,
            )),
        )
        .route(
            "/api/plugins/:id/update",
            post(plugins::update_plugin).layer(axum_mw::from_fn_with_state(
                state.clone(),
                middleware::require_auth,
            )),
        )
        .route(
            "/api/plugins/:id",
            delete(plugins::uninstall_plugin).layer(axum_mw::from_fn_with_state(
                state.clone(),
                middleware::require_auth,
            )),
        )
        .route(
            "/api/plugins/:id/toggle",
            put(plugins::toggle_plugin).layer(axum_mw::from_fn_with_state(
                state.clone(),
                middleware::require_auth,
            )),
        )
        .route(
            "/api/plugins/:id/test",
            post(plugins::test_plugin).layer(axum_mw::from_fn_with_state(
                state.clone(),
                middleware::require_auth,
            )),
        )
        .route(
            "/api/plugins/:id/health",
            get(plugins::get_plugin_health).layer(axum_mw::from_fn_with_state(
                state.clone(),
                middleware::require_auth,
            )),
        )
        .route(
            "/api/plugins/:id/tool-policy",
            put(plugins::update_plugin_tool_policy).layer(axum_mw::from_fn_with_state(
                state.clone(),
                middleware::require_auth,
            )),
        )
        .route(
            "/api/plugins/migrate-legacy/:id",
            post(plugins::migrate_legacy_mcp_server).layer(axum_mw::from_fn_with_state(
                state.clone(),
                middleware::require_auth,
            )),
        )
        .route(
            "/api/admin/plugins/integrate/draft",
            post(plugins::draft_plugin_integration).layer(axum_mw::from_fn_with_state(
                state.clone(),
                middleware::require_admin,
            )),
        )
        .route(
            "/api/admin/plugins/integrate/publish",
            post(plugins::publish_plugin_integration).layer(axum_mw::from_fn_with_state(
                state.clone(),
                middleware::require_admin,
            )),
        )
}
