//! Route knowledge base e code-wiki.
//!
//! Estratte da `main.rs` durante il refactor del god-file. Nessun
//! cambiamento di path, metodo HTTP, handler o middleware.

use crate::routes::prelude::*;
use crate::*;

pub fn merge(router: Router<AppState>, state: &AppState) -> Router<AppState> {
    router
        // ── knowledge ─────────────────────────────────────────
        .route(
            "/api/projects/:id/knowledge/notes",
            get(knowledge::routes::list_notes).layer(axum_mw::from_fn_with_state(
                state.clone(),
                middleware::require_auth,
            )),
        )
        .route(
            "/api/projects/:id/knowledge/notes/:note_id/revisions",
            get(docs_core::routes::proj_list_revisions).layer(axum_mw::from_fn_with_state(
                state.clone(),
                middleware::require_auth,
            )),
        )
        .route(
            "/api/projects/:id/knowledge/notes/:note_id/revisions/:version",
            get(docs_core::routes::proj_get_revision).layer(axum_mw::from_fn_with_state(
                state.clone(),
                middleware::require_auth,
            )),
        )
        .route(
            "/api/projects/:id/knowledge/notes/:note_id/diff",
            get(docs_core::routes::proj_diff).layer(axum_mw::from_fn_with_state(
                state.clone(),
                middleware::require_auth,
            )),
        )
        .route(
            "/api/projects/:id/knowledge/notes/:note_id/restore",
            post(docs_core::routes::proj_restore).layer(axum_mw::from_fn_with_state(
                state.clone(),
                middleware::require_auth,
            )),
        )
        .route(
            "/api/projects/:id/knowledge/notes/:note_id",
            get(knowledge::routes::get_note)
                .patch(knowledge::routes::patch_note)
                .delete(knowledge::routes::delete_note)
                .layer(axum_mw::from_fn_with_state(
                    state.clone(),
                    middleware::require_auth,
                )),
        )
        .route(
            "/api/projects/:id/knowledge/similar",
            post(knowledge::routes::similar_handler).layer(axum_mw::from_fn_with_state(
                state.clone(),
                middleware::require_auth,
            )),
        )
        // W2 code-wiki: genera la documentazione AI per-file del progetto.
        .route(
            "/api/projects/:id/knowledge/code-wiki/generate",
            post(knowledge::code_doc::generate_code_wiki_handler).layer(
                axum_mw::from_fn_with_state(state.clone(), middleware::require_auth),
            ),
        )
        // M15.3 — Edit manuale dei todo di un run (traccia edited_by, ri-emette
        // TodoUpdated + PlanUpdated). Gated da agent.todos.user_editable.
        .route(
            "/api/projects/:id/agent/todos/:run_id/edit",
            post(agent_todos_routes::edit_todo).layer(axum_mw::from_fn_with_state(
                state.clone(),
                middleware::require_auth,
            )),
        )
        .route(
            "/api/projects/:id/knowledge/links",
            post(knowledge::routes::create_link).layer(axum_mw::from_fn_with_state(
                state.clone(),
                middleware::require_auth,
            )),
        )
        .route(
            "/api/projects/:id/knowledge/links/:link_id",
            axum::routing::delete(knowledge::routes::delete_link).layer(
                axum_mw::from_fn_with_state(state.clone(), middleware::require_auth),
            ),
        )
        .route(
            "/api/projects/:id/knowledge/tags",
            get(knowledge::routes::list_tags).layer(axum_mw::from_fn_with_state(
                state.clone(),
                middleware::require_auth,
            )),
        )
        .route(
            "/api/projects/:id/knowledge/graph",
            get(knowledge::routes::graph_handler).layer(axum_mw::from_fn_with_state(
                state.clone(),
                middleware::require_auth,
            )),
        )
        .route(
            "/api/projects/:id/knowledge/recompute-links",
            post(knowledge::routes::recompute_links).layer(axum_mw::from_fn_with_state(
                state.clone(),
                middleware::require_auth,
            )),
        )
        .route(
            "/api/projects/:id/knowledge/rebuild",
            post(knowledge::routes::rebuild_knowledge).layer(axum_mw::from_fn_with_state(
                state.clone(),
                middleware::require_auth,
            )),
        )
        .route(
            "/api/projects/:id/knowledge/generate-rich",
            post(knowledge::routes::generate_rich_kb).layer(axum_mw::from_fn_with_state(
                state.clone(),
                middleware::require_auth,
            )),
        )
        .route(
            "/api/projects/:id/knowledge/extract-functional",
            post(knowledge::routes::extract_functional_handler).layer(axum_mw::from_fn_with_state(
                state.clone(),
                middleware::require_auth,
            )),
        )
        .route(
            "/api/projects/:id/knowledge/init-or-refresh",
            post(knowledge::routes::init_or_refresh_knowledge).layer(axum_mw::from_fn_with_state(
                state.clone(),
                middleware::require_auth,
            )),
        )
        .route(
            "/api/projects/:id/knowledge/notes/manual",
            post(knowledge::routes::create_note_manual).layer(axum_mw::from_fn_with_state(
                state.clone(),
                middleware::require_auth,
            )),
        )
        .route(
            "/api/projects/:id/knowledge/obsidian-vault",
            get(knowledge::routes::get_obsidian_vault)
                .put(knowledge::routes::put_obsidian_vault)
                .layer(axum_mw::from_fn_with_state(
                    state.clone(),
                    middleware::require_auth,
                )),
        )
}
