[package]
name = "doc-service"
edition.workspace = true
version.workspace = true

[[bin]]
name = "doc-service"
path = "src/main.rs"

[dependencies]
anyhow.workspace = true
axum.workspace = true
chrono.workspace = true
dotenvy.workspace = true
nexus-auth = { path = "../nexus-auth" }
nexus-types = { path = "../nexus-types" }
reqwest.workspace = true
nexus-http.workspace = true
serde.workspace = true
serde_json.workspace = true
sqlx.workspace = true
tokio.workspace = true
tower-http.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
uuid.workspace = true

[lints]
workspace = true
