[package]
name = "nexus-types"
edition.workspace = true
version.workspace = true

[dependencies]
anyhow.workspace = true
regex.workspace = true
axum.workspace = true
chrono.workspace = true
nexus-auth = { path = "../nexus-auth" }
nexus-cache = { path = "../nexus-cache" }
reqwest.workspace = true
serde.workspace = true
serde_json.workspace = true
sqlx.workspace = true
tokio.workspace = true
tracing.workspace = true
uuid.workspace = true

[lints]
workspace = true
