[package]
name = "nexus-types"
edition.workspace = true
version.workspace = true

[dependencies]
axum.workspace = true
nexus-auth = { path = "../nexus-auth" }
nexus-cache = { path = "../nexus-cache" }
serde.workspace = true
serde_json.workspace = true
sqlx.workspace = true
tracing.workspace = true
uuid.workspace = true
