[package]
name = "nexus-auth"
edition.workspace = true
version.workspace = true

[dependencies]
anyhow.workspace = true
axum.workspace = true
nexus-cache = { path = "../nexus-cache" }
jsonwebtoken.workspace = true
rand.workspace = true
serde.workspace = true
sha2.workspace = true
sqlx.workspace = true
thiserror = "1.0"
tokio.workspace = true
tracing.workspace = true

[dev-dependencies]
uuid.workspace = true

[lints]
workspace = true
