[package]
name = "chat-service"
edition.workspace = true
version.workspace = true

[[bin]]
name = "chat-service"
path = "src/main.rs"

[dependencies]
anyhow.workspace = true
axum.workspace = true
chrono.workspace = true
dashmap.workspace = true
dotenvy.workspace = true
futures.workspace = true
nexus-auth = { path = "../nexus-auth" }
nexus-types = { path = "../nexus-types" }
prost.workspace = true
redis.workspace = true
regex.workspace = true
reqwest.workspace = true
serde.workspace = true
serde_json.workspace = true
sha2.workspace = true
sqlx.workspace = true
tokio.workspace = true
tokio-stream.workspace = true
tonic.workspace = true
tower.workspace = true
tower-http.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
uuid.workspace = true
mcp-proto = { path = "../mcp-proto" }
