"use client";

// KnowledgeNavigator — navigatore leggero a 1 colonna per la sidebar IDE.
// Sostituisce il KnowledgeWorkspace (layout 3 colonne) che nello spazio stretto
// della sidebar diventava ingestibile (albero + colonna centrale vuota).
//
// Riusa gli stessi mattoni della KB full-page (regola H, no duplicazione):
//   - listDocs / WikiDoc da lib/wiki-client.ts
//   - buildTree + WikiTreeNodeView (display con tooltip completo e tag kind)
// Al click su un documento NON si apre nella sidebar stretta: si naviga alla
// pagina full-page /projects/{id}/kb?doc={docId}, dove la KB 3 colonne ha spazio.

import * as React from "react";
import { listDocs, type WikiDoc } from "../../lib/wiki-client";
import { buildTree, type WikiDocSummary } from "../wiki/wiki-scope";
import { WikiTreeNodeView } from "../wiki/wiki-tree";
import { useThemeColors } from "../../lib/theme";
import { useI18n } from "../../lib/i18n";
import { useProjectStore, selectKnowledgeChangedAt } from "../../lib/project-dispatcher";

interface Props {
  projectId: string;
}

function docToSummary(d: WikiDoc): WikiDocSummary {
  return {
    id: d.id,
    title: d.title,
    path: d.vault_file_path ?? "",
    category: d.kind,
    tags: d.tags ?? [],
    autoGenerated: d.auto_generated,
    updatedAt: d.updated_at,
  };
}

export function KnowledgeNavigator({ projectId }: Props) {
  const tc = useThemeColors();
  const { t } = useI18n();

  const [docs, setDocs] = React.useState<WikiDoc[]>([]);
  const [loading, setLoading] = React.useState(false);
  const [error, setError] = React.useState<string | null>(null);
  const [filter, setFilter] = React.useState("");

  const knowledgeChangedAt = useProjectStore(selectKnowledgeChangedAt);

  const loadDocs = React.useCallback(() => {
    setLoading(true);
    setError(null);
    return listDocs({ scope: "project", project_id: projectId, limit: 1000 })
      .then((r) => {
        setDocs(r.items);
      })
      .catch((e: unknown) => {
        setError(e instanceof Error ? e.message : String(e));
      })
      .finally(() => {
        setLoading(false);
      });
  }, [projectId]);

  React.useEffect(() => {
    void loadDocs();
  }, [loadDocs, knowledgeChangedAt]);

  const tree = React.useMemo(() => {
    const f = filter.trim().toLowerCase();
    const summaries = docs.map(docToSummary);
    const filtered = f
      ? summaries.filter(
          (s) =>
            s.title.toLowerCase().includes(f) ||
            (s.path || "").toLowerCase().includes(f),
        )
      : summaries;
    return buildTree(filtered);
  }, [docs, filter]);

  // Click su un doc: apri la KB full-page gia' posizionata sul documento.
  const openDoc = React.useCallback(
    (docId: string) => {
      window.location.href = `/projects/${projectId}/kb?doc=${encodeURIComponent(docId)}`;
    },
    [projectId],
  );

  return (
    <div
      style={{
        flex: 1,
        minHeight: 0,
        minWidth: 0,
        display: "flex",
        flexDirection: "column",
        overflow: "hidden",
      }}
    >
      <div
        style={{
          flexShrink: 0,
          padding: "8px 10px",
          borderBottom: `1px solid ${tc.border}`,
          display: "flex",
          flexDirection: "column",
          gap: 6,
        }}
      >
        <input
          value={filter}
          onChange={(e) => setFilter(e.target.value)}
          placeholder={t("wiki.tree.filter")}
          style={{
            width: "100%",
            minWidth: 0,
            boxSizing: "border-box",
            padding: "5px 8px",
            background: tc.bgInput,
            border: `1px solid ${tc.border}`,
            color: tc.text,
            borderRadius: 4,
            fontSize: 12,
          }}
        />
        <div style={{ fontSize: 11, color: tc.textSecondary }}>
          {docs.length} {t("wiki.tree.docs")} · {t("wiki.nav.open_hint")}
        </div>
      </div>

      <div style={{ flex: 1, minHeight: 0, minWidth: 0, overflowY: "auto", overflowX: "hidden", padding: "6px 0" }}>
        {loading ? (
          <div style={{ padding: 12, color: tc.textSecondary, fontSize: 12 }}>
            {t("wiki.loading")}
          </div>
        ) : error ? (
          <div style={{ padding: 12, color: tc.error, fontSize: 12 }}>{error}</div>
        ) : docs.length === 0 ? (
          <div style={{ padding: 12, color: tc.textSecondary, fontSize: 12 }}>
            {t("wiki.nav.empty")}
          </div>
        ) : (
          <WikiTreeNodeView
            node={tree}
            depth={0}
            selectedId={null}
            onSelect={openDoc}
            // Tutti i gruppi top-level partono COMPRESSI all'apertura del
            // pannello laterale Knowledge. Lo stato di apertura/chiusura viene
            // persistito per progetto in localStorage (chiave
            // `wiki:project:<projectId>:<path>`), cosi' al re-render successivo
            // il pannello ricorda cosa aveva aperto l'utente.
            persistKey={`wiki:project:${projectId}`}
          />
        )}
      </div>
    </div>
  );
}
